### ISSUE TITLE
Unresolved symbol - CVFolds

### ISSUE THREAD

**Issue by skn123** [Shark-ML/Shark#10]
Having built shark.dll, I tried to build an example CVFolds. With a previous version of the code, It built and ran without any problems. However, now there are some link errors.
Error	1	error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl shark::IRpropPlus::IRpropPlus(void)" (__imp_??0IRpropPlus@shark@@QEAA@XZ) referenced in function "double __cdecl trainProblem(class shark::LabeledData<class shark::blas::vector<double>,class shark::blas::vector<double> > const &,class shark::LabeledData<class shark::blas::vector<double>,class shark::blas::vector<double> > const &,double)" (?trainProblem@@YANAEBV?$LabeledData@V?$vector@N@blas@shark@@V123@@shark@@0N@Z)	F:\Binaries\VS2013\Shark\examples\CVFolds.obj	CVFolds
Error	2	error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual void __cdecl shark::IRpropPlus::init(class shark::AbstractObjectiveFunction<class shark::blas::vector<double>,double> &,class shark::blas::vector<double> const &)" (__imp_?init@IRpropPlus@shark@@UEAAXAEAV?$AbstractObjectiveFunction@V?$vector@N@blas@shark@@N@2@AEBV?$vector@N@blas@2@@Z) referenced in function "double __cdecl trainProblem(class shark::LabeledData<class shark::blas::vector<double>,class shark::blas::vector<double> > const &,class shark::LabeledData<class shark::blas::vector<double>,class shark::blas::vector<double> > const &,double)" (?trainProblem@@YANAEBV?$LabeledData@V?$vector@N@blas@shark@@V123@@shark@@0N@Z)	F:\Binaries\VS2013\Shark\examples\CVFolds.obj	CVFolds
Error	3	error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual void __cdecl shark::IRpropPlus::step(class shark::AbstractObjectiveFunction<class shark::blas::vector<double>,double> const &)" (__imp_?step@IRpropPlus@shark@@UEAAXAEBV?$AbstractObjectiveFunction@V?$vector@N@blas@shark@@N@2@@Z) referenced in function "double __cdecl trainProblem(class shark::LabeledData<class shark::blas::vector<double>,class shark::blas::vector<double> > const &,class shark::LabeledData<class shark::blas::vector<double>,class shark::blas::vector<double> > const &,double)" (?trainProblem@@YANAEBV?$LabeledData@V?$vector@N@blas@shark@@V123@@shark@@0N@Z)	F:\Binaries\VS2013\Shark\examples\CVFolds.obj	CVFolds
Error	4	error LNK1120: 3 unresolved externals	F:\Binaries\VS2013\Shark\bin\Release\CVFolds.exe	1	1	CVFolds

**Comment by skn123** [comment]
Making this change in the main CMakeLists.txt file fixed the issue:

if(BUILD_SHARED_LIBS)
  IF(NOT MSVC)
    set(SHARK_USE_DYNLIB 1)
  ELSE()
    ADD_DEFINITIONS(-DSHARK_USE_DYNLIB)
  ENDIF()
endif()

**Comment by Ulfgard** [comment]
how do you build the examples? just typing make examples? or do you copy it into your own projects and then call it?

Your workaround will not work for external project as you work around 

set(SHARK_USE_DYNLIB 1)

which sets the correct defines in shark/Core/Shark.h 

if you use a build directory you will likely need to install shark (make install) before you can use it with an external project as otherwise the Shark.h is not at its right place (and maybe the system picks up an old Shark.h?) 

this is hard to trouble shoot, i have not found a system where our build files failed in that regard...

**Comment by skn123** [comment]
Yes, indeed I do make install before I use it in an external project. We also have a visual studio equivalent of make install.

**Comment by Ulfgard** [comment]
could you try what happens - without your workaround if you add in the first line of CVFolds.cpp 

#include<shark/Core/Shark.h>

If this fixes the issue there might be some problem regarding the include order and i have a point to investigate. If this does not help, can you verify whether

SHARK_USE_DYNLIB is defined in shark/Core/Shark.h?

**Comment by skn123** [comment]
This does not help
Error	1	error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl shark::IRpropPlus::IRpropPlus(void)" (__imp_??0IRpropPlus@shark@@QEAA@XZ) referenced in function "double __cdecl trainProblem(class shark::LabeledData<class shark::blas::vector<double>,class shark::blas::vector<double> > const &,class shark::LabeledData<class shark::blas::vector<double>,class shark::blas::vector<double> > const &,double)" (?trainProblem@@YANAEBV?$LabeledData@V?$vector@N@blas@shark@@V123@@shark@@0N@Z)	F:\Binaries\VS2013\Shark\examples\CVFolds.obj	CVFolds
Error	2	error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual void __cdecl shark::IRpropPlus::init(class shark::AbstractObjectiveFunction<class shark::blas::vector<double>,double> &,class shark::blas::vector<double> const &)" (__imp_?init@IRpropPlus@shark@@UEAAXAEAV?$AbstractObjectiveFunction@V?$vector@N@blas@shark@@N@2@AEBV?$vector@N@blas@2@@Z) referenced in function "double __cdecl trainProblem(class shark::LabeledData<class shark::blas::vector<double>,class shark::blas::vector<double> > const &,class shark::LabeledData<class shark::blas::vector<double>,class shark::blas::vector<double> > const &,double)" (?trainProblem@@YANAEBV?$LabeledData@V?$vector@N@blas@shark@@V123@@shark@@0N@Z)	F:\Binaries\VS2013\Shark\examples\CVFolds.obj	CVFolds
Error	3	error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual void __cdecl shark::IRpropPlus::step(class shark::AbstractObjectiveFunction<class shark::blas::vector<double>,double> const &)" (__imp_?step@IRpropPlus@shark@@UEAAXAEBV?$AbstractObjectiveFunction@V?$vector@N@blas@shark@@N@2@@Z) referenced in function "double __cdecl trainProblem(class shark::LabeledData<class shark::blas::vector<double>,class shark::blas::vector<double> > const &,class shark::LabeledData<class shark::blas::vector<double>,class shark::blas::vector<double> > const &,double)" (?trainProblem@@YANAEBV?$LabeledData@V?$vector@N@blas@shark@@V123@@shark@@0N@Z)	F:\Binaries\VS2013\Shark\examples\CVFolds.obj	CVFolds
Error	4	error LNK1120: 3 unresolved externals	F:\Binaries\VS2013\Shark\bin\Release\CVFolds.exe	CVFolds

![without_fix](https://cloud.githubusercontent.com/assets/4594354/10824929/99a68ab0-7e88-11e5-82ef-903f468b970a.jpg)

and if I apply the fix

![with_fix](https://cloud.githubusercontent.com/assets/4594354/10824941/a825af80-7e88-11e5-88dd-0c9cd2aa4ffa.jpg)

The problem is not in Shark.h
but in DllSupport.h

**Comment by skn123** [comment]
I get the same errors.
No change happens when I include the files. I think the problem lies with DllSupport.h
Here are two screenshots of what happens with and without my fix.

![with_fix](https://cloud.githubusercontent.com/assets/4594354/10826868/c81d8f3e-7e91-11e5-9916-d783875b168a.jpg)
![without_fix](https://cloud.githubusercontent.com/assets/4594354/10826876/cf8b5d78-7e91-11e5-99da-44672a9a48fc.jpg)

**Comment by Ulfgard** [comment]
Hi, I think there is something wrong with your setup. You see the problem in Shark.h line 99: somehow your cmake believes that SHARK_USE_DYNLIB == 0 and therefore deactivates the define (Which explains why you needed to include the define explicitely). You can see that when you go to Core/Shark.h.in which has this in line 99:

 #cmakedefine SHARK_USE_DYNLIB

The generation is triggered by
set(SHARK_USE_DYNLIB 1)

together with

configure_file (
	"${CMAKE_SOURCE_DIR}/include/shark/Core/Shark.h.in"
	"${CMAKE_BINARY_DIR}/include/shark/Core/Shark.h"
)

in the CMakeLists.txt

I have to investigate what might cause this as on my windows test system (msvc 13) i could generate a dynamic shark just fine a few days ago

could you try to regenerate the shark project to test this? e.g. choose a new folder run cmake-gui and set BUILD_SHARED_LIBS to see whether this will generate the "right" Shark.h?

**Comment by Ulfgard** [comment]
okay, I had time to take a look at that. Apparently, we did not include Shark.h in DLLSupport.h or that line got somehow lost. Anyway, it is fixed now.

Thanks for the report!
