### ISSUE TITLE
Segmentation fault when training regressiontree

### ISSUE THREAD

**Issue by jakobht** [Shark-ML/Shark#105]
The program below segfaults due to unbounded calls of CARTTrainer::measureStrength

The program loads input points from the data array declared first, and creates 0 labels for all inputs.

It then tries to learn a regression tree for this data.

The program segfaults in the CARTTrainer::pruneTree method due to unbounded recursive calls of measureStrength (probably because the learned tree has a loop).

I'm not sure if I'm doing something stupid or if it is a bug in the Trainer. 
I have successfully trained other datasets without problems.
The issue is both present in the Release from the website and when cloning from github. 

My platform is Arch linux 
Gcc version 6.1.1
I compile with command:
`g++  -g example.cpp  -lboost_serialization -lshark`

There are 80 points in the data array but I found that it still breaks with 72 points (but not with 71 points).

The program (apparently Github does not allow me to attach a cpp file):

```c++
#include <shark/Algorithms/Trainers/CARTTrainer.h>
#include <iostream>

using namespace std; 
using namespace shark;

double data[] = {
    0,2.49213,2.49213,0,
0,2.95446,2.95446,0,
0,2.77123,2.77123,0,
0,2.11444,2.11444,0,
0,2.63859,2.63859,0,
0,2.19116,2.19116,0,
0,2.0851,2.0851,0,
0,2.13839,2.13839,0,
0,2.73129,2.73129,0,
0,2.21937,2.21937,0,
0,2.10212,2.10212,0,
0,2.74708,2.74708,0,
0,2.81297,2.81297,0,
0,2.55067,2.55067,0,
0,2.82431,2.82431,0,
0,2.88559,2.88559,0,
0,2.21894,2.21894,0,
0,2.80792,2.80792,0,
0,2.23107,2.23107,0,
0,2.1189,2.1189,0,
0,2.40597,2.40597,0,
0,2.02819,2.02819,0,
0,2.93205,2.93205,0,
0,2.02587,2.02587,0,
0,2.23181,2.23181,0,
0,2.02214,2.02214,0,
0,2.3436,2.3436,0,
0,2.51296,2.51296,0,
0,2.27819,2.27819,0,
0,2.04024,2.04024,0,
0,2.00951,2.00951,0,
0,2.18167,2.18167,0,
0,2.15445,2.15445,0,
0,2.8293,2.8293,0,
0,2.35753,2.35753,0,
0,2.55998,2.55998,0,
0,2.50951,2.50951,0,
0,2.57271,2.57271,0,
0,2.25947,2.25947,0,
0,2.36144,2.36144,0,
0,2.1499,2.1499,0,
0,2.93502,2.93502,0,
0,2.91247,2.91247,0,
0,2.86219,2.86219,0,
0,2.13033,2.13033,0,
0,2.24625,2.24625,0,
0,2.28152,2.28152,0,
0,2.64267,2.64267,0,
0,2.44395,2.44395,0,
0,2.9154,2.9154,0,
0,2.27155,2.27155,0,
0,2.75356,2.75356,0,
0,2.06892,2.06892,0,
0,2.63929,2.63929,0,
0,2.03277,2.03277,0,
0,2.9277,2.9277,0,
0,2.77907,2.77907,0,
0,2.5104,2.5104,0,
0,2.42026,2.42026,0,
0,2.07923,2.07923,0,
0,2.09489,2.09489,0,
0,2.38659,2.38659,0,
0,2.25424,2.25424,0,
0,2.69799,2.69799,0,
0,2.06669,2.06669,0,
0,2.33084,2.33084,0,
0,2.87783,2.87783,0,
0,2.80559,2.80559,0,
0,2.27803,2.27803,0,
0,2.204,2.204,0,
0,2.64382,2.64382,0,
0,2.5916,2.5916,0,
0,2.11713,2.11713,0,
0,2.54628,2.54628,0,
0,2.64049,2.64049,0,
0,2.1585,2.1585,0,
0,2.0147,2.0147,0,
0,2.98601,2.98601,0,
0,2.55336,2.55336,0,
0,2.1967,2.1967,0
};

int main() {

    std::vector<RealVector> inputs;
    std::vector<RealVector> labels;

    // Prepare the inputs
    for(size_t i = 0; i < 72*4; i+=4)
    {
        RealVector v(4);
        for(size_t j = 0; j < 4; j++)
        {
            v(j) = data[i+j];
        }
        inputs.push_back(v);
    }
    
    // Prepare the labels
    for(size_t i = 0; i < 72; i++)
    {
        RealVector v(1);
        v(0) = 0;
        labels.push_back(v);
    }

    // Print the prepared data
    for(auto point : inputs)
    {
        std::cout << point << endl;
    }

    for(auto point : labels)
    {
        std::cout << point << endl;
    }

    RegressionDataset data = createLabeledDataFromRange(inputs, labels);
    
    cout << "Training set - number of data points: " << data.numberOfElements()
         << " input dimension: " << inputDimension(data) << endl;
    
    //Train the model
    CARTTrainer trainer;
    CARTClassifier<RealVector> model;
    trainer.train(model, data);
}
```

**Comment by jakobht** [comment]
I have played around with the program a bit more and I have the following observations:

1. If I compile shark to debug the program hits an assertion in `Shark/include/shark/Data/Impl/Dataset.inl` line 389:
``Shark/include/shark/Data/Impl/Dataset.inl:389: void shark::detail::SharedContainer<Type>::repartition(const Range&) [with Range = std::vector<long unsigned int>; Type = shark::blas::vector<double>]: Assertion `isIndependent()' failed.``

    This is true for all sizes of data from 10 to 80.

2. If the size of the data is less than 10 I get a floating point exception which comes from a division by zero in `Shark/include/shark/Data/Impl/Dataset.inl` line 74.

These things seams to be a problem regardless of what the actual number in the matrices are.

**Comment by chivesman** [comment]
The isIndependent() assertion is because the dataset is shadow copied to remove constness in CARTTrainer.cpp:29, not optimal but seems unrelated to the problem afterwords.
