### ISSUE TITLE
Test failures with 3.1.x

### ISSUE THREAD

**Issue by ghisvail** [Shark-ML/Shark#110]
I finally managed to update the release of `shark` in Debian to the latest stable release (3.1.1). The build logs for all supported architectures are available [here](https://buildd.debian.org/status/logs.php?pkg=shark&ver=3.1.1%2Bds1-1). There are a couple of recurring failures though:

First, the `DirectSearch_RealCodedNSGAII` and `DirectSearch_SMS-EMOA` testcases hit the time limit on a few architectures. Please consider [labeling](https://cmake.org/cmake/help/v3.0/prop_test/LABELS.html) these tests (and possibly others) as slow, so they can be easily excluded via the `-LE` flag in `ctest`. 

Then, the failures in `Core_Math` and `BLAS_Vector_Expression` (pasted below) suggests that the tolerances used are not portable to lower precisions. It is probably not a coincidence that these tests succeed on all 64-bit architectures and fail on their 32-bit sibling. 

Perhaps these problems are already fixed on the tip of `master`. In this case, perhaps it would be worth release a new stable version?

Cheers,

`BLAS_Vector_Expression` errors:

```
  9/169 Test   #9: BLAS_Vector_Expression .......................***Failed    0.15 sec
Running 39 test cases...
/«BUILDDIR»/shark-3.1.1+ds1/Test/LinAlg/BLAS/vector_expression.cpp(410): error: in "LinAlg_BLAS_vector_expression/BLAS_Sparse_Vector_Sqr": absolute value of *posOp-*posResult{4} exceeds 0.0001
/«BUILDDIR»/shark-3.1.1+ds1/Test/LinAlg/BLAS/vector_expression.cpp(410): error: in "LinAlg_BLAS_vector_expression/BLAS_Sparse_Vector_Sqr": absolute value of *posOp-*posResult{1} exceeds 0.0001
/«BUILDDIR»/shark-3.1.1+ds1/Test/LinAlg/BLAS/vector_expression.cpp(410): error: in "LinAlg_BLAS_vector_expression/BLAS_Sparse_Vector_Sqr": absolute value of *posOp-*posResult{4} exceeds 0.0001
/«BUILDDIR»/shark-3.1.1+ds1/Test/LinAlg/BLAS/vector_expression.cpp(410): error: in "LinAlg_BLAS_vector_expression/BLAS_Sparse_Vector_Sqr": absolute value of *posOp-*posResult{9} exceeds 0.0001
/«BUILDDIR»/shark-3.1.1+ds1/Test/LinAlg/BLAS/vector_expression.cpp(410): error: in "LinAlg_BLAS_vector_expression/BLAS_Sparse_Vector_Sqr": absolute value of *posOp-*posResult{16} exceeds 0.0001
/«BUILDDIR»/shark-3.1.1+ds1/Test/LinAlg/BLAS/vector_expression.cpp(410): error: in "LinAlg_BLAS_vector_expression/BLAS_Sparse_Vector_Sqr": absolute value of *posOp-*posResult{25} exceeds 0.0001
/«BUILDDIR»/shark-3.1.1+ds1/Test/LinAlg/BLAS/vector_expression.cpp(410): error: in "LinAlg_BLAS_vector_expression/BLAS_Sparse_Vector_Sqr": absolute value of *posOp-*posResult{36} exceeds 0.0001

*** 7 failures are detected in the test module "BLAS_Vector_vector_expression"
```

`Core_Math` errors:

```
115/169 Test #118: Core_Math ....................................***Failed    0.31 sec
Running 3 test cases...
0.25 17.1973 17.1973
0.5 4.9348 4.9348
1 1.64493 1.64493
1.5 0.934802 0.934802
0.0005 -1.6e+10 -1.6e+10
0.25 -129.328 -129.328
0.5 -16.8288 -16.8288
1 -2.40411 -2.40411
1.5 -0.828797 -0.828797
2 -0.404114 -0.404114
10 -0.0110498 -0.0110498
/«BUILDDIR»/shark-3.1.1+ds1/Test/Core/Math.cpp(58): error: in "Core_Math/Math_Trigamma_Random": difference{1.01679e-07} between y{0.23214611484357095} and yEst{0.232146091239116} exceeds 1e-05%

*** 1 failure is detected in the test module "Core_Math"
```

**Comment by ghisvail** [comment]
Apparently, commits 96da1643f9ae384c3be670409f2870de9aded8e4 and f30f92f43aef33bebd81080d059ff3ade3deb484 were not enough.

**Comment by Ulfgard** [comment]
Hi,

i backported a rather large number of your pull requests, fixed the tolerances and added the "slow" label to a number of tests. Everything should be in the tag v3.1.2

https://github.com/Shark-ML/Shark/releases/tag/v3.1.2

Hope this fixes this! Thanks again!

**Comment by ghisvail** [comment]
Nice, gonna try this out soon. Thanks for the prompt response.

**Comment by ghisvail** [comment]
The `BLAS_Vector_Expression` tests still fail on 32-bit architectures. Build logs are available [here](https://buildd.debian.org/status/logs.php?pkg=shark&ver=3.1.2%2Bds1-1).

**Comment by Ulfgard** [comment]
Hm, this might be a real bug as there should not be so large errors in this test. I have to check what is failing there

**Comment by ghisvail** [comment]
Do you think it comes from a defect in the testsuite or in the library itself?

**Comment by Ulfgard** [comment]
I think i found the issue. we have

x(i) = -i+3.0;

but i is an unsigned long long. so -i is something very large positive, so the square will result in something very very large=> problems.

x(i) = -double(i)+3.0;

fixes that.

**Comment by Ulfgard** [comment]
https://github.com/Shark-ML/Shark/releases/tag/v3.1.3

**Comment by ghisvail** [comment]
Cheers, I'll update and report back.

**Comment by ghisvail** [comment]
All good. Update submitted. Thanks for your prompt response on this.

**Comment by ghisvail** [comment]
Re-opening, some tolerance errors were found in the `RBM_GaussianLayer` test case on Ubuntu builds.

https://launchpadlibrarian.net/282429562/buildlog_ubuntu-yakkety-ppc64el.shark_3.1.3+ds1-1_BUILDING.txt.gz

**Comment by Ulfgard** [comment]
(curses)

**Comment by Ulfgard** [comment]
was this fixed? i do not remember.

**Comment by ghisvail** [comment]
Yes, this was due to a bug in the `gcc` code optimization produced on `powerpc64le`.

**Comment by Ulfgard** [comment]
thanks! one issue less!
