### ISSUE TITLE
Missing range constructor in `vector`

### ISSUE THREAD

**Issue by LucHermitte** [Shark-ML/Shark#111]
Hi,

I see in https://github.com/Shark-ML/Shark/commit/54a0c4a8cd9d91163a68f015184b2781913ffe02#diff-5660c3e9a5eaf0179e70a63fe00c9c2aL87 that the range  constructor of `shark::blass::vector` has been removed.

You should be able to revert this change safely. From C++98 to C++17, `std::vector` still has this constructor (4). It's perfectly compatible with C++11. See http://en.cppreference.com/w/cpp/container/vector/vector

Having it will permit code such as:

```c++
std::vector<RealVector> v;
float const* b = &*SomeNonStandardContainer.Begin();
v.emplace_back(b, b+SomeNonStandardContainer.Size());
```

**Comment by Ulfgard** [comment]
should be in there now :)

**Comment by LucHermitte** [comment]
Thank you!
