### ISSUE TITLE
Compile-time error

### ISSUE THREAD

**Issue by ManiAm** [Shark-ML/Shark#115]
After git pull, I notices that I am having trouble compiling the shark library. The svn version I used is 'Sep 16, 2016'. Here is the compile-time error I got:

![selection_015](https://cloud.githubusercontent.com/assets/5473998/18601997/188d75c4-7c1b-11e6-91b8-6d406bacb677.png)

I am running Ubuntu 14 LTS x64.

**Comment by Ulfgard** [comment]
Hi,

you had bad luck today. I just broke it. I can only fix it tomorrow. try the latest tag, that works fine :)

Best,
Oswin
________________________________
