### ISSUE TITLE
matrix_assign.hpp line 395 396 

### ISSUE THREAD

**Issue by 01wa** [Shark-ML/Shark#116]
shark::blas::detail::internal_transpose_proxy<M> transM(m());
shark::blas::detail::internal_transpose_proxy<E const> transE(e());

**Comment by Ulfgard** [comment]
Hi, 

is there any problem? btw the line goes:

```
detail::internal_transpose_proxy<M> transM(m());
detail::internal_transpose_proxy<E const> transE(e());
```

**Comment by Ulfgard** [comment]
okaz. I am now understanding. MSVC does not find the internal_transpose_proxy for some reason any more which requires adding the explicit namespace. I solved it now bz removen the proxz class and using trans()+auto

**Comment by 01wa** [comment]
Hi,
Namespacehave a problem,
detail::internal_transpose_proxy<M> transM(m());
detail::internal_transpose_proxy<E const> transE(e());
Expressed as
 shark::blas::kernels:detail::internal_transpose_proxy<M> transM(m());
 shark::blas::kernels::detail::internal_transpose_proxy<E const> transE(e());

  it should be

  shark::blas::detail::internal_transpose_proxy<M> transM(m());
  shark::blas::detail::internal_transpose_proxy<E const> transE(e());







At 2016-09-18 15:04:18,"Oswin Krause" <notifications@github.com> wrote:


Hi,

is there any problem? btw the line goes:

detail::internal_transpose_proxy<M> transM(m());
detail::internal_transpose_proxy<E const> transE(e());
