### ISSUE TITLE
Offset term in CSvmTrainer after setStructure

### ISSUE THREAD

**Issue by Dawidk** [Shark-ML/Shark#118]
I implemented the Divide and Conquer Algorithm from http://www.cs.utexas.edu/~cjhsieh/dcsvm/ and have a small problem regarding the bias term.

Since the paper suggests not to train with the bias term, I set the boolean for the trainer to "false". This setting also carries over to the step where I do a "warm-start" with inner SVMs. To do that I provide the alpha-vector from previous trainings.

For the warm-start I do the following:

```
KernelClassifier<RealVector> kc;
kc.decisionFunction().setStructure(base_type::m_kernel, train_data.inputs(), this->m_trainOffset);
```

After this I can set the alpha vector of the decision function. This however throws an exception in CSvmTrainer.h in line 162:

```
else f.offset() = RealVector();
```

with

```
RealVector& offset(){
        SHARK_CHECK(hasOffset(), "[KernelExpansion::offset] invalid call for object without offset term");
        return m_b;
    }
```

Setting the bias to "true" in setStructure solves the problem, but I don't know if the bias will be ignored while training, since the trainer is still set to "false".

**Comment by Ulfgard** [comment]
oh thats a bug on our side. Sorry. I will fix it asap. You are using the development version, right?

**Comment by Dawidk** [comment]
Seems I'm using release. 3.1.0. Updated from github after the warm start bug fix on Jul 10th.

**Comment by Ulfgard** [comment]
I have just commited the fix: i removed the line.

**Comment by TGlas** [comment]
Great, that was fast! We should probably cover this in a unit test before closing the issue.

**Comment by Ulfgard** [comment]
fixed.
