### ISSUE TITLE
LNK1104	cannot open file 'D:\Shark-3.1.0\lib\Debug\shark_debug.lib'	ExampleProject

### ISSUE THREAD

**Issue by royTheFredo** [Shark-ML/Shark#119]
I'm setting up Shark for the first time and encountered this linker error on building the example project. 
LNK1104	cannot open file 'D:\Shark-3.1.0\lib\Debug\shark_debug.lib'	ExampleProject
It appears that this question has been answered in the SourceForge forums, but they give a 404 now that Shark moved to Github. I used the CMake GUI for Example project and added an entry for D:/Shark-3.1.0/SharkConfig.cmake after receiving errors from CMake on the first Configuration attempt. Generate completed without issue. I then opened the resulting VS solution file and attempted a build. The linker error is valid since that shark_debug.lib file doesn't exist anywhere.
I've been spoiled by installation files for everything in the Windows environment and I could have missed something in compiling and setting up Boost or Shark. When would shark_debug.lib have been created? Can I retry from that point or am I doomed to a full re-installation?

Environment:
Windows 10
Visual Studio 2015
Shark 3.1.0
Boost 1.62

**Comment by Ulfgard** [comment]
you should build the library first before trying to use it. there should be a BUILD ALL target or similar in the project list :)
________________________________

**Comment by royTheFredo** [comment]
Uh oh, my n00b-ness is showing. That seems to have done the trick. Thanks for the help.
All .tpp files are now .cpp and the following appeared after a poisonous "system("pause");" was added to HelloWorld.cpp and ExampleProject.exe was run. If this is what I **should** see, I'll move forward with the tutorials. 

{
    "version": {
        "major": "3",
        "minor": "0",
        "patch": "0"
    },
    "isOfficialRelease": "false",
    "platform": "Win32",
    "compiler": "Microsoft Visual C++ version 14.0",
    "stdLib": "Dinkumware standard library version 650",
    "boostVersion": {
        "major": "1",
        "minor": "62",
        "patch": "0"
    },
    "buildType": "Debug",
    "dynamicBuild": "false",
    "hasOpenMp": "true"
}

**Comment by Ulfgard** [comment]
Hi,

everything is fine!

Best,
Oswin
________________________________
