### ISSUE TITLE
a link error only occurs in some examples

### ISSUE THREAD

**Issue by zhuang-hao-ming** [Shark-ML/Shark#120]
hello!

I build the shark with **boost lib64-msvc-10.0**  ,**shark3.0.0**  ,**vs2010 64bit**. it succeed. when i try to run an example, i include the **C:\local\boost_1_59_0** and **E:\test\shark\shark_proj\include**   **E:\test\shark\shark_proj\include** and link 
```
shark.lib,
C:\local\boost_1_59_0\lib64-msvc-10.0\boost_system-vc100-mt-1_59.lib
C:\local\boost_1_59_0\lib64-msvc-10.0\boost_date_time-vc100-mt-1_59.lib
C:\local\boost_1_59_0\lib64-msvc-10.0\boost_filesystem-vc100-mt-1_59.lib
C:\local\boost_1_59_0\lib64-msvc-10.0\boost_program_options-vc100-mt-1_59.lib
C:\local\boost_1_59_0\lib64-msvc-10.0\boost_serialization-vc100-mt-1_59.lib
C:\local\boost_1_59_0\lib64-msvc-10.0\boost_thread-vc100-mt-1_59.lib
C:\local\boost_1_59_0\lib64-msvc-10.0\boost_unit_test_framework-vc100-mt-1_59.lib
C:\local\boost_1_59_0\lib64-msvc-10.0\boost_chrono-vc100-mt-1_59.lib
C:\local\boost_1_59_0\lib64-msvc-10.0\boost_atomic-vc100-mt-1_59.lib
```
and use the boost marco **BOOST_ALL_NO_LIB**.  it succeed for the **tsp** exmple. but for the other example like **FFNet** it fail and occur error messages like below:
```
错误	14	error LNK2001: 无法解析的外部符号 "public: virtual bool __thiscall boost::serialization::typeid_system::extended_type_info_typeid_0::is_equal(class boost::serialization::extended_type_info const &)const " (?is_equal@extended_type_info_typeid_0@typeid_system@serialization@boost@@UBE_NABVextended_type_info@34@@Z)	E:\test\10_12\shark_3\shark_3\main.obj	shark_3
错误	13	error LNK2001: 无法解析的外部符号 "public: virtual bool __thiscall boost::serialization::typeid_system::extended_type_info_typeid_0::is_less_than(class boost::serialization::extended_type_info const &)const " (?is_less_than@extended_type_info_typeid_0@typeid_system@serialization@boost@@UBE_NABVextended_type_info@34@@Z)	E:\test\10_12\shark_3\shark_3\main.obj	shark_3
```

i want to ask:
- i found someone can just include the boost library, and use boost's auto link , but when i just include the boost library i end up with a error: lib cannot open. why?
- is the bits of the library serious , i create a **win32 console project**, and use **vs2010 64**,  **lib64-msvc-10.0**
- if i want to build boost myself , is it necessary to build for specific compiler or just run the .bat and b2.exe without any parameters

very thanks

**Comment by Ulfgard** [comment]
Hi,

does it work with the provided example CMakeLists.txt? see examples/ExampleProject.

You said you are using shark 3.0.0 this is outdated, the latest release is 3.1.3

https://github.com/Shark-ML/Shark/releases/tag/v3.1.3

Best,
Oswin

________________________________

**Comment by zhuang-hao-ming** [comment]
i finally resolve this problem, it is that i create a **win32 console application** and build it in **debug** mode but the shark library its **64bits** and build in **release** mode.  i changed my application to **x64** and build it in **release** mode, in the end it succeed.

thanks
haoming

**Comment by Ulfgard** [comment]
great,

I close this then!
