### ISSUE TITLE
how to use RFTrainer with weighted labels

### ISSUE THREAD

**Issue by SkyBluues** [Shark-ML/Shark#126]
Dear Shark Community,

I want to train my model by RFTrainer with weighted labels,but looking at parameter list, i can not find the parameter that weighting the label. So whether shark'RFTrainer could be trained using weighted labels like opencv.
Thanks for your help.

**Comment by Ulfgard** [comment]
Hi Sky,

This is unfortunately not supported yet. It is on our todo list as the RFTrainer is on our overhaul list anyways. Some care has to be taken when doing subsetting especially with weight distributions that are heavy tailed(e.g. do we want to sample OOB sets that have approximately the same weight or the same number of samples?)
