### ISSUE TITLE
Cannot find file Shark.h when building in Visual Studio

### ISSUE THREAD

**Issue by ehockedy** [Shark-ML/Shark#127]
Hi,

Having followed the installation instructions at http://image.diku.dk/shark/sphinx_pages/build/html/rest_sources/getting_started/installation.html#windows-and-visual-studio , I have generated the build files in CMake and now need to actually build them in Visual Studio 2015. However, when I try to build I get Error	C1083 "Cannot open include file: 'shark/Core/Shark.h': No such file or directory". It cannot find the Shark.h file because it doesn't exist. In 'shark/Core' there does exist 'Shark.h.in', but when changing that to 'Shark.h', it produces an 'invalid preprocessor command 'cmakedefine'' error. Same with changing source file to include <shark/Core/Shark.h.in>.

Anyone know a fix, what to do about this, or even a better way to install Shark so that I can use the library with my own C++ code?

Any help greatly appreciated.

**Comment by Ulfgard** [comment]
Hi,

which version are you using? latest development? in any case there should be a file that has been auto generated in your build directory (e.g. Shark/build/include/shark/Core/Shark.h). This *should* be added as an include in your projects automatically, if it has not, you have to wait until i am back from my christmas vacation to fix this for good. I have no VS here.

for now you should be able to work around it by putting your build directory in the same directory of the CMakeLists.txt. Alternatively you can copy that file over. Be aware that every time you change the configuration, you will have to copy it, too.

**Comment by ehockedy** [comment]
Hey, thank for you reply.

So I've managed to solve the issue. Previously I was using the source downloaded from the website download page (http://image.diku.dk/shark/sphinx_pages/build/html/rest_sources/downloads/downloads.html), but I tried using the source directly from GitHub which ended up working (I think I also did something wrong with my cmake build location in the original instance). 
When building the github code in Visual Studio there was one error regarding tolower() in Downloader.hpp, but I solved this by changing std::tolower() to ::tolower(). This then built successfully and I was able to complete the installation.

Also just a quick remark, I feel the installation guide is insufficient in explaining how to actually install the library (since it finishes after the build files have been generated in cmake). Having never had to install from source before, I was not aware the steps needed to be taken to install through Visual Studio (i.e. once generated in cmake, open the shark solution file in visual studio, then building in both Debug and Release mode, and finally building the INSTALL project on its own, possibly running in administrator if required depending on where the installation files are to be written and what rights are required). This is probably obvious for professional developers, but for someone who has never done it before it would certainly be useful.

**Comment by Ulfgard** [comment]
Hi,

good to know that you resolved this. the reason we did not describe the install is simply because it is not needed in windows (and i think no-one ever tried to install it in windows). most people just build shark and then create their own project using examples/ExampleProject (where you have to set Shark_DIR to your shark build directory)

**Comment by ehockedy** [comment]
Ah yes I see now, that certainly would have saved me some hassle! I should have not disregarded the "Your Shark programs" page so quickly - I wrongly assumed that it was something to do after the full installation so assumed it wasn't helpful for me. As you can probably tell I'm still getting to grips with this whole installing from source, building things,cmake,  makefiles, Visual Studio, etc. thing, but this whole experience has taught me a lot. 
Thanks again for you comments
