### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by hwang-happy** [Shark-ML/Shark#129]
hi sharkers, i encountered install problems on centos like below, could you help me to solve this problem ? thank you very much .

[  5%] Building CXX object src/CMakeFiles/shark.dir/ObjectiveFunctions/ROC.cpp.o
[  6%] Linking CXX static library ../lib/libshark.a
[  6%] Built target shark
Scanning dependencies of target SharkVersion
[  7%] Building CXX object src/CMakeFiles/SharkVersion.dir/Core/Version.cpp.o
[  7%] Linking CXX executable ../bin/SharkVersion

/home/hwang/softwear/Programe/libc++/boost1.57.0/lib/libboost_date_time.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'
/home/hwang/softwear/Programe/libc++/boost1.57.0/lib/libboost_filesystem.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/hwang/softwear/Programe/libc++/boost1.57.0/lib/libboost_thread.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/home/hwang/softwear/Programe/libc++/boost1.57.0/lib/libboost_program_options.so: undefined reference to `std::basic_istream<wchar_t, std::char_traits<wchar_t> >& std::getline<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >(std::basic_istream<wchar_t, std::char_traits<wchar_t> >&, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, wchar_t)@GLIBCXX_3.4.21'
/home/hwang/softwear/Programe/libc++/boost1.57.0/lib/libboost_program_options.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21'
collect2: ld returned 1 exit status
make[2]: *** [bin/SharkVersion] Error 1
make[1]: *** [src/CMakeFiles/SharkVersion.dir/all] Error 2
make: *** [all] Error 2

**Comment by Ulfgard** [comment]
Hi,

I think the problem is that boost is built for C++11 while cmake is not telling the compiler to do the same. therefore it links the old C++03 libraries and not its C++11 version. You can try downloading the master branch which is now by default C++11. This should fix it.

**Comment by hwang-happy** [comment]
thanks, i am a newer, what is  "the master branch" ?

**Comment by hwang-happy** [comment]
Is my boost library installed wrong or the parameter of cmake for Shark wrong ? thank you very much

**Comment by Ulfgard** [comment]
master branch at github, e.g. this download: https://github.com/Shark-ML/Shark/archive/master.zip

I don't know whats wrong, yet. if the download does not work we can still check your boost libraries.

**Comment by hwang-happy** [comment]
thanks,
when i using the "master branch" ，I met with some difficulties.

install command: cmake "-DBOOST_ROOT=/home/hwang/softwear/Programe/libc++/boost1.62.0"  "-DCMAKE_INSTALL_PREFIX=/home/hwang/softwear/Programe/libc++/Shark.3.0.0" >cmkael.log 2>error

**## Cmake return below:**
-- The C compiler identification is GNU 4.1.2
-- The CXX compiler identification is GNU 4.1.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Will build: Release
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   serialization
--   filesystem
--   system
-- Using boost from
-- OpenMP found
-- HDF5 not found, skip
-- No usable CBLAS Library found. No fast linear Algebra used.
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hwang/softwear/Programe/ins-libc++/Shark-master/build


**## Then make**   
**return below:**
In file included from /home/hwang/softwear/Programe/ins-libc++/Shark-master/src/Algorithms/CARTTrainer.cpp:8:
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Algorithms/Trainers/CARTTrainer.h:43:25: error: unordered_map: No such file or directory
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:225: error: ‘is_const’ is not a membeof ‘std’
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:225: error: ‘is_const’ is not a membeof ‘std’
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:225: error: template argument 1 is invalid
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:225: error: expected unqualified-id before ‘,’ token
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:262: error: ISO C++ forbids declaration of ‘reference’ with no type
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:262: error: expected ‘;’ before ‘opeor’
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Data/Dataset.h:902: error: expected `;' before end of line
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Data/Dataset.h:902: error: expected `}' before end of line
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp: In constructor ‘shark::blas::indexed_terator<Closure>::indexed_iterator(Closure, size_t)’:
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:233: error: class ‘shark::blas::indexe_iterator<Closure>’ does not have any field named ‘m_index’
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:233: error: class ‘shark::blas::indexe_iterator<Closure>’ does not have any field named ‘m_closure’
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp: In constructor ‘shark::blas::indexed_terator<Closure>::indexed_iterator(const shark::blas::indexed_iterator<C>&)’:
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:237: error: class ‘shark::blas::indexe_iterator<Closure>’ does not have any field named ‘m_index’
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:237: error: class ‘shark::blas::indexe_iterator<Closure>’ does not have any field named ‘m_closure’
make[2]: *** [src/CMakeFiles/shark.dir/Algorithms/CARTTrainer.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/shark.dir/all] Error 2
make: *** [all] Error 2


**could you please help me to solve this error, thank you**

**Comment by hwang-happy** [comment]
thanks,
when i using the "master branch" ，I met with some difficulties.

install command: cmake "-DBOOST_ROOT=/home/hwang/softwear/Programe/libc++/boost1.62.0"  "-DCMAKE_INSTALL_PREFIX=/home/hwang/softwear/Programe/libc++/Shark.3.0.0" >cmkael.log 2>error

**## Cmake return below:**
-- The C compiler identification is GNU 4.1.2
-- The CXX compiler identification is GNU 4.1.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Will build: Release
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   serialization
--   filesystem
--   system
-- Using boost from
-- OpenMP found
-- HDF5 not found, skip
-- No usable CBLAS Library found. No fast linear Algebra used.
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hwang/softwear/Programe/ins-libc++/Shark-master/build


**## Then make**   
**return below:**
In file included from /home/hwang/softwear/Programe/ins-libc++/Shark-master/src/Algorithms/CARTTrainer.cpp:8:
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Algorithms/Trainers/CARTTrainer.h:43:25: error: unordered_map: No such file or directory
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:225: error: ‘is_const’ is not a membeof ‘std’
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:225: error: ‘is_const’ is not a membeof ‘std’
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:225: error: template argument 1 is invalid
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:225: error: expected unqualified-id before ‘,’ token
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:262: error: ISO C++ forbids declaration of ‘reference’ with no type
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:262: error: expected ‘;’ before ‘opeor’
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Data/Dataset.h:902: error: expected `;' before end of line
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Data/Dataset.h:902: error: expected `}' before end of line
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp: In constructor ‘shark::blas::indexed_terator<Closure>::indexed_iterator(Closure, size_t)’:
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:233: error: class ‘shark::blas::indexe_iterator<Closure>’ does not have any field named ‘m_index’
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:233: error: class ‘shark::blas::indexe_iterator<Closure>’ does not have any field named ‘m_closure’
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp: In constructor ‘shark::blas::indexed_terator<Closure>::indexed_iterator(const shark::blas::indexed_iterator<C>&)’:
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:237: error: class ‘shark::blas::indexe_iterator<Closure>’ does not have any field named ‘m_index’
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/LinAlg/BLAS/detail/iterator.hpp:237: error: class ‘shark::blas::indexe_iterator<Closure>’ does not have any field named ‘m_closure’
make[2]: *** [src/CMakeFiles/shark.dir/Algorithms/CARTTrainer.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/shark.dir/all] Error 2
make: *** [all] Error 2


**could you please help me to solve this error, thank you**

**Comment by Ulfgard** [comment]
is this fixed?
