### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by hwang-happy** [Shark-ML/Shark#130]
hi sharkers,
when i am install shark-ML of centos, i encounter some trouble.

below is my install command,
cmake "-DBOOST_ROOT=/home/hwang/softwear/Programe/libc++/boost1.62.0"  
"-DCMAKE_INSTALL_PREFIX=/home/hwang/softwear/Programe/libc++/boost1.62.0" ../ 

below is returns:
-- The C compiler identification is GNU 4.1.2
-- The CXX compiler identification is GNU 4.1.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Will build: Release
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   serialization
--   filesystem
--   system
-- Using boost from
-- OpenMP found
-- HDF5 not found, skip
-- No usable CBLAS Library found. No fast linear Algebra used.
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hwang/softwear/Programe/ins-libc++/Shark-master/build

/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Data/Dataset.h: At global scope:
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Data/Dataset.h:902: error: expected unqualified-id before end of line
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Data/Dataset.h:902: error: expected `}' before end of line
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Data/Dataset.h:902: error: expected `}' before end of line
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Data/Dataset.h:902: error: expected declaration before end of line
make[2]: *** [src/CMakeFiles/shark.dir/Algorithms/CARTTrainer.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/shark.dir/all] Error 2
make: *** [all] Error 2

**Comment by Ulfgard** [comment]
at which target does this happen? what do you compile? i only see the cmake command not any make...

**Comment by hwang-happy** [comment]
This error happended when i use make after cmake, I think cmake is ok error happens after make.

**Comment by Ulfgard** [comment]
I still need to know at which target this happens. the log is not complete. Please attach the complete error log.
________________________________

**Comment by hwang-happy** [comment]
Ok, the gcc version of my cluster is 5.3.0 located at use/local/bin. Cmake version is 3.4.0. 

When I type command 
cmake "-DBOOST_ROOT=/home/hwang/softwear/Programe/libc++/boost1.62.0"
"-DCMAKE_INSTALL_PREFIX=/home/hwang/softwear/Programe/libc++/boost1.62.0" ../

below is returns:
-- The C compiler identification is GNU 4.1.2
-- The CXX compiler identification is GNU 4.1.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Will build: Release
-- Boost version: 1.62.0
-- Found the following Boost libraries:
-- serialization
-- filesystem
-- system
-- Using boost from
-- OpenMP found
-- HDF5 not found, skip
-- No usable CBLAS Library found. No fast linear Algebra used.
-- Boost version: 1.62.0
-- Found the following Boost libraries:
-- unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hwang/softwear/Programe/ins-libc++/Shark-master/build



When I type make
Below is return
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Data/Dataset.h: At global scope:
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Data/Dataset.h:902: error: expected unqualified-id before end of line
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Data/Dataset.h:902: error: expected }' before end of line /home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Data/Dataset.h:902: error: expected}' before end of line
/home/hwang/softwear/Programe/ins-libc++/Shark-master/include/shark/Data/Dataset.h:902: error: expected declaration before end of line
make[2]: *** [src/CMakeFiles/shark.dir/Algorithms/CARTTrainer.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/shark.dir/all] Error 2
make: *** [all] Error 2

**Comment by Ulfgard** [comment]
Hi,

I have looked closer at your cmake output and realized that your gcc is version 4.1.2, released February 13, 2007, nearly 10 years old. This compiler is not supported by shark as it has too many bugs and limitations. Please update to a more recent compiler, gcc or clang. 

closing this as this is the error.
