### ISSUE TITLE
libboost_serialization-gcc51-mt-1_62.so.1.62.0 error

### ISSUE THREAD

**Issue by hwang-happy** [Shark-ML/Shark#131]
hi, sharkers

I use the cmake to install Shark
cmake "-DBOOST_ROOT=/home/hwang/softwear/Programe/libc++/boost1.62.0"  
"-DCMAKE_INSTALL_PREFIX=/home/hwang/softwear/Programe/libc++/shark" ../

it return below
-- The C compiler identification is GNU 5.1.0
-- The CXX compiler identification is GNU 5.1.0
-- Check for working C compiler: /home/hwang/softwear/Programe/gcc-5.1.0/bin/cc
-- Check for working C compiler: /home/hwang/softwear/Programe/gcc-5.1.0/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/hwang/softwear/Programe/gcc-5.1.0/bin/c++
-- Check for working CXX compiler: /home/hwang/softwear/Programe/gcc-5.1.0/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Will build: Release
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   serialization
--   filesystem
--   system
-- Using boost from
-- OpenMP found
-- HDF5 not found, skip
-- No usable CBLAS Library found. No fast linear Algebra used.
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hwang/softwear/Programe/ins-libc++/Shark-master/build

And then use the "make" command, everything is ok like below
[ 98%] Built target Models_MeanModel
Scanning dependencies of target LinAlg_Repeat
[ 98%] Building CXX object Test/CMakeFiles/LinAlg_Repeat.dir/LinAlg/repeat.cpp.o
[100%] Linking CXX executable ../bin/LinAlg_Repeat
[100%] Built target LinAlg_Repeat
Scanning dependencies of target Models_Softmax
[100%] Building CXX object Test/CMakeFiles/Models_Softmax.dir/Models/Softmax.cpp.o
[100%] Linking CXX executable ../bin/Models_Softmax
[100%] Built target Models_Softmax

and then cd /home/hwang/softwear/Programe/libc++/shark/bin
./SharkVersion
it return ./SharkVersion: error while loading shared libraries: libboost_serialization-gcc51-mt-1_62.so.1.62.0: cannot open shared object file: No such file or directory

but in my boost directory /home/hwang/softwear/Programe/libc++/boost1.62.0
hwang@console:boost1.62.0$ find ./ | grep libboost_serialization-gcc51-mt-1_62.so.1.62.0
./lib/libboost_serialization-gcc51-mt-1_62.so.1.62.0
so it is exits in my boost directory.

how can i solve this problem? thanks for your patience help.

**Comment by hwang-happy** [comment]
hi, sharkers

I use the cmake to install Shark
**cmake "-DBOOST_ROOT=/home/hwang/softwear/Programe/libc++/boost1.62.0"
"-DCMAKE_INSTALL_PREFIX=/home/hwang/softwear/Programe/libc++/shark" ../**

it return below
-- The C compiler identification is GNU 5.1.0
-- The CXX compiler identification is GNU 5.1.0
-- Check for working C compiler: /home/hwang/softwear/Programe/gcc-5.1.0/bin/cc
-- Check for working C compiler: /home/hwang/softwear/Programe/gcc-5.1.0/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/hwang/softwear/Programe/gcc-5.1.0/bin/c++
-- Check for working CXX compiler: /home/hwang/softwear/Programe/gcc-5.1.0/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Will build: Release
-- Boost version: 1.62.0
-- Found the following Boost libraries:
-- serialization
-- filesystem
-- system
-- Using boost from
-- OpenMP found
-- HDF5 not found, skip
-- No usable CBLAS Library found. No fast linear Algebra used.
-- Boost version: 1.62.0
-- Found the following Boost libraries:
-- unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hwang/softwear/Programe/ins-libc++/Shark-master/build

And then use the "make" command, everything is ok like below
[ 98%] Built target Models_MeanModel
Scanning dependencies of target LinAlg_Repeat
[ 98%] Building CXX object Test/CMakeFiles/LinAlg_Repeat.dir/LinAlg/repeat.cpp.o
[100%] Linking CXX executable ../bin/LinAlg_Repeat
[100%] Built target LinAlg_Repeat
Scanning dependencies of target Models_Softmax
[100%] Building CXX object Test/CMakeFiles/Models_Softmax.dir/Models/Softmax.cpp.o
[100%] Linking CXX executable ../bin/Models_Softmax
[100%] Built target Models_Softmax

**and then cd /home/hwang/softwear/Programe/libc++/shark/bin
./SharkVersion
it return ./SharkVersion: error while loading shared libraries: libboost_serialization-gcc51-mt-1_62.so.1.62.0: cannot open shared object file: No such file or directory

but in my boost directory /home/hwang/softwear/Programe/libc++/boost1.62.0
hwang@console:boost1.62.0$ find ./ | grep libboost_serialization-gcc51-mt-1_62.so.1.62.0
./lib/libboost_serialization-gcc51-mt-1_62.so.1.62.0
so it is exits in my boost directory.**

how can i solve this problem? thanks for your patience help.

**Comment by Ulfgard** [comment]
you have to tell your dynamic loader where to find the boost libraries. e.g. 

LD_LIBRARY_PATH=/home/hwang/softwear/Programe/libc++/boost1.62.0 ./SharkVersion

for more information, see

http://unix.stackexchange.com/questions/22926/where-do-executables-look-for-shared-objects-at-runtime
