### ISSUE TITLE
Throw archive_exception when read classifier model from file

### ISSUE THREAD

**Issue by mickey9294** [Shark-ML/Shark#133]
I'm using RFTrainer to train a RFClassifier model to do classification. I save the model to local files according to tutorial [Serialization](http://image.diku.dk/shark/sphinx_pages/build/html/rest_sources/tutorials/concepts/misc/serialization.html). But when I try to read the model I have saved, it throws a boost::archive::archive_exception. 
I really wonder what is wrong. Could anyone help me? I'll really appreciate it!
Following is the codes I use to train RFClassifier and read it from file:
```
#include <iostream>
#include <fstream>
#include <shark/Data/Dataset.h>
#include <shark/Data/Csv.h>
#include <shark/Algorithms/Trainers/RFTrainer.h> //the random forest trainer

typedef shark::Data<shark::RealVector>::element_range PREDICT_Elements;
typedef shark::Data<shark::RealVector>::const_element_reference PREDICT_ElementRef;

void train()
{
	shark::RFTrainer trainer;
	shark::RFClassifier classifier;

	shark::ClassificationDataset training_data;
	shark::importCSV(training_data, "dataset.csv",
		shark::LAST_COLUMN, ',');

	trainer.train(classifier, training_data);

	std::ofstream model_out("rfclassifier.model");
	if (model_out.is_open())
	{
		boost::archive::polymorphic_text_oarchive oa(model_out);
		classifier.write(oa);
		model_out.close();
	}
}

void test()
{
	shark::RFClassifier classifier;

	std::ifstream ifs("rfclassifier.model");
	if (ifs.is_open())
	{
		boost::archive::polymorphic_text_iarchive ia(ifs);
		classifier.read(ia);
		ifs.close();
	}
}

int main(int argc, char **argv)
{
	//train();
	test();

	system("PAUSE");
	return 0;
}
```

And the snapshot of the exception, the dataset(in .csv file) I use, and the classifier model file I have trained is as below:
![exception](https://cloud.githubusercontent.com/assets/9548699/21581636/54f5cd14-d075-11e6-8260-a85b5acb2dc8.PNG)
data file:
https://drive.google.com/open?id=0B8kVqzi6lrp4enNfczFuMW9jSE0
classifier model file:
https://drive.google.com/open?id=0B8kVqzi6lrp4YXJZeUZJQXhDNEE

**Comment by mickey9294** [comment]
No one knows what is wrong?

**Comment by Ulfgard** [comment]
Well, around new years, people tend to travel :)

I am looking at it now.
________________________________

**Comment by mickey9294** [comment]
@Ulfgard Okay.thank you really really much :)

**Comment by Ulfgard** [comment]
Hi,

there are missing/nan-values in your file. Most Shark algorithms can not handle missing values and we are just assuming that all are there. Maybe we should add a check for it and bail out if we find nans.
I have no ideas what the trees are going to do with those values, but boost serialization certainly can not cope with it:

https://svn.boost.org/trac/boost/ticket/9810

Quote:

"this has been discussed for years. It's not a problem of the serialization library per se. It's an effect of the fact that there is no standard/portable way for text based streams to represent various types of NaN s. no one has shown an interest is addressing this. So for now the best policy is to trap attempts so serialize Nan's to text base archives. "

The resolution is to remove missing values by replacing them with whatever heuristic you like, or remove rows/columns including nans. (about 8800 of your 222500 data points include nan, so this would be an option, same as the columns: only one column seem to include nan values). But note that, when removing rows, you will still not be able to apply the model a data point which includes a nan. I have tested it and the program runs fine when removing the rows.

There are plans to add support for missing values in the trees at some point in the future, but this is not on a high priority yet.

________________________________

**Comment by mickey9294** [comment]
@Ulfgard  Thanks a loooot. You are rigtht. I finally fix it up!

**Comment by Ulfgard** [comment]
good to hear!
Closing this.
