### ISSUE TITLE
Cannot construct OnlineRNNet because pure virtual function in AbstractModel is undefined

### ISSUE THREAD

**Issue by jharlacher** [Shark-ML/Shark#134]
This seems like a bug - the following function is undefined in AbstractModel:

virtual void eval(BatchInputType const & patterns, BatchOutputType& outputs, State& state) const = 0;

So this program does not compile:
#include <shark/Core/Shark.h>
#include <shark/Models/RecurrentStructure.h>
#include <shark/Models/OnlineRNNet.h>

int main(int argc, char *argv[])
{
    shark::RecurrentStructure rec_str;
    shark::OnlineRNNet online_rnn(&rec_str);
    return 0;
}

However if I use RNNet it does compile:
#include <shark/Core/Shark.h>
#include <shark/Models/RecurrentStructure.h>
#include <shark/Models/RNNet.h>

int main(int argc, char *argv[])
{
    shark::RecurrentStructure rec_str;
    shark::RNNet rnn(&rec_str);
    return 0;
}

**Comment by Ulfgard** [comment]
oh, this is indeed a bug. Thanks for pointing this out. I have no imediate solution for this right now.

**Comment by Ulfgard** [comment]
Hi,

just to inform you, I am on it. Problem is that all of this requires unit testing which is not very easy to do. Guess this is why i skipped this, which of course is a bad idea.

**Comment by jharlacher** [comment]
Thanks for the update.

**Comment by Ulfgard** [comment]
I finished the testing and fixed a bit of a bug. We unfortunately forgot to port this through our reworks.

I am not 100% happy with how this played out, because the model interface is not really made for stateful models. The way this works is using a State object and batches of size 1.

```
//create the model
RecurrentStructure structure;
structure.set_structure(inputs,hidden,outputs,true_for_bias);
OnlineRNNet model(&structure, true_for_gradients);
//start a new sequence
auto state = model.createState();//state stores the internal state. so new state object=new sequence
RealMatrix input(1,model.inputSize());
RealMatrix output(1,model.outputSize());
while(...){
    noalias(row(input,0)) = new_input_state();
    model.eval(input,output,*state);
    //if you want to compute the derivative at the current step:
    RealVector gradient;
    model.weightedParameterDerivative(input,output,loss_derivative,state, gradient);
}
```
