### ISSUE TITLE
Issue with building shark?

### ISSUE THREAD

**Issue by mohammadAdnan** [Shark-ML/Shark#141]
Hello, i got the following error when i tried to build shark both using cmd or cmake GUI:

C:\Users\Avrahim\Documents\Visual Studio 2015\Projects\Shark-3.0.0\build>cmake  -G "Visual Studio 14 2015 Win64" -DBOOST_INCLUDEDIR:PATH="C:\Users\Avrahim\Documents\Visual Studio 2015\Projects\Shark-3.0.0\packages\boost.1.63.0.0\lib\native\include" -DBOOST_LIBRARYDIR:PATH="C:\Users\Avrahim\Documents\Visual Studio 2015\Projects\Shark-3.0.0\packages\boost_libs"  -DDEBUG=OFF -DPROFILE=OFF ..
-- The C compiler identification is MSVC 19.0.24213.1
-- The CXX compiler identification is MSVC 19.0.24213.1
-- Check for working C compiler: F:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: F:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: F:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: F:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Will build: release
CMake Warning at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:146 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:146 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:146 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:146 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:146 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:146 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:146 (find_package)

-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1812 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:146 (find_package)

CMake Error at CMakeLists.txt:154 (message):
  Please make sure Boost 1.48.0 is installed on your system

-- Configuring incomplete, errors occurred!
See also "C:/Users/Avrahim/Documents/Visual Studio 2015/Projects/Shark-3.0.0/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Avrahim/Documents/Visual Studio 2015/Projects/Shark-3.0.0/build/CMakeFiles/CMakeError.log".

**Comment by Ulfgard** [comment]
Hi,

this looks like a problem of cmake finding your boost header. I can not really see what the issue is. You should check that the headers are actuaally at the right palce. I see that the two paths you give differ quite a lot (once with boost.1.63.0.0 and once with boost_libs). so make sure that this is actually correct.

**Comment by mohammadAdnan** [comment]
Hey Ulfgard, i understand, but you can check it:
https://mega.nz/#!IQgDDC7b!GH8vIpJ9VyyUAz7-Te_wt9GhvXSPErWyceiW5wlKrp4

**Comment by Ulfgard** [comment]
Hi,

this is not helping. you have other paths in your CMake-Gui and i do not actually see the part of the error message outlining what it could not find. Also, i do not see the files that are found in the path. e.g. you do not set the include directory, so the system assumes that your headers are in BOOST_ROOT/include/boost/ is that the case?

**Comment by mohammadAdnan** [comment]
Ah, okay, here it's:

The C compiler identification is MSVC 19.0.24213.1
The CXX compiler identification is MSVC 19.0.24213.1
Check for working C compiler: F:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working C compiler: F:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: F:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working CXX compiler: F:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Will build: Release
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1812 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.59.0

  Boost include path: C:/local/boost_1.59

  Could not find the following Boost libraries:

          boost_system
          boost_date_time
          boost_filesystem
          boost_program_options
          boost_serialization
          boost_thread
          boost_unit_test_framework

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:142 (find_package)


CMake Error at CMakeLists.txt:150 (message):
  Please make sure Boost 1.48.0 is installed on your system


Configuring incomplete, errors occurred!
See also "C:/Users/Avrahim/Documents/Visual Studio 2015/Projects/Shark-3.1.0/build/CMakeFiles/CMakeOutput.log".

**Comment by Ulfgard** [comment]
same again: please check that the files are actually there in your file system. It tells you that for the config given it can not find the library files. Is that correct? What is the path to the boost_system lib for example?

**Comment by mohammadAdnan** [comment]
Yeah Ulfgard, all the files there. I set the path in system variable too. I followed all the steps here:

http://image.diku.dk/shark/sphinx_pages/build/html/rest_sources/getting_started/installation.html#windows-and-visual-studio

**Comment by mohammadAdnan** [comment]
Hello Ulfgard, this is the path to the boost libraries and i make sure all the files really exist:

C:\local\boost_1.59\lib64-msvc-12.0

**Comment by mohammadAdnan** [comment]
Thanks Ulfgard, i downloaded all the dependencies and then built it using cmake from cmd. I tried out your first example of how to get start, i included the bath to shark include folder in my project, here the picture:

https://mega.nz/#!NNoVVQBT!3YKw5AhizMWiqYyl8jD_PbJHSgfH85qEJX5gnPwhYWA

**Comment by gino0717** [comment]
I found that lib in boost would be named like
`boost_system-vc141-mt-1_64.lib`

but cmake can only find

`boost_system.lib`

rename all the file may solve some problem
