### ISSUE TITLE
make failed on version 3.1.3

### ISSUE THREAD

**Issue by Mike-Feng** [Shark-ML/Shark#146]
I used this guide to install Shark: http://image.diku.dk/shark/sphinx_pages/build/html/rest_sources/getting_started/installation.html#
`mkdir Shark/build/
cd Shark/build
cmake ../
make`

the cmake command is OK. but the make command failed.
I am using ubuntu16.04.    
it shows the blew picture:
/usr/include/cblas.h:25:22: note: ‘CBLAS_ORDER’ has a previous declaration here
 typedef CBLAS_LAYOUT CBLAS_ORDER; /* this for backward compatibility with CBLAS
![screenshot from 2017-02-05 10-42-09](https://cloud.githubusercontent.com/assets/11884093/22623281/09ceb842-eb90-11e6-9f25-0bdf165f11ee.png)

I can install 3.0.0. It is make OK, and I got a libshark.a file in the lib folder.
But, when I use it in my qt project, qt creator told me, there is no clapack.h.  But I found this file in usr/include/atlas folder.  And, after I copied this file from usr/include/atlas  to usr/include. another errors occurs like above screenshot. Does any one can help?

**Comment by Mike-Feng** [comment]
update: I just execute this command to fix this error:
`sudo cp /usr/include/atlas/*.* /usr/include`
this error down, but another errors up. I will keep trying........

**Comment by Mike-Feng** [comment]
Above is a stupid action. it doesn't resolve problem.

**Comment by Mike-Feng** [comment]
Why shark lib cannot find atlas header files?

**Comment by Ulfgard** [comment]
probably because they are in paths that shark does not know about. every linux distribution is doing this differently.
________________________________

**Comment by Mike-Feng** [comment]
Thank you Uifgard, I have successfully resolved this issue last night. 
After I specific the include path 
`/usr/include/atlas`
, and I also add the libs in my QT project: 
`LIBS += -lshark -lboost_serialization -lcblas -latlas`
then, magic is coming.

**Comment by Ulfgard** [comment]
great to hear!

Best,
Oswin
