### ISSUE TITLE
issue  on load/save model

### ISSUE THREAD

**Issue by Mike-Feng** [Shark-ML/Shark#148]
There are several models in my project, I want to write just one method to save/load them, because all of them have save/load method.
I DONOT  use generic <T>. 
I declared this function in .h file:
`public:
    void SaveModel(std::string filename, ISerializable &lda, int version = 1);
    void LoadModel(std::string filename, ISerializable &lda, int version = 1);`
and here is implement:
`void MLbySharkAPI::SaveModel(std::string filename, ISerializable &lda, int version)
{
    try
    {
        // save the model to the file filename
        std::filebuf fb;
        fb.open (filename,std::ios::out);
        std::ostream os2(&fb);
        TextOutArchive ofs(os2);
        lda.save(ofs,1);
        fb.close();
    }catch(...)
    {
        DEBUG("SaveModel failed!");
    }
}`

the file content is just one line:
22 serialization::archive 12
How to fix this issue?
Another ps:
I change the lda.save(ofs,1) to lda.write(ofs).  It works.
But, how to make the save method work?

**Comment by Ulfgard** [comment]
neither save, nor write are for direct use.

`std::oftream of(filename); 
TextOutArchive ofs(of); 
ofs << lda;`
