### ISSUE TITLE
KernelBudgetedSGDTrainer is not a test

### ISSUE THREAD

**Issue by Ulfgard** [Shark-ML/Shark#150]
It never checks any results

**Comment by aydindemircioglu** [comment]
mmh, actually it does, but throws stupidly an exception there.
i'll fix this within the next weeks.

**Comment by aydindemircioglu** [comment]
i see you already have fixed that, i add an additional check for the error rate.

**Comment by Ulfgard** [comment]
yeah, now it tests something. I was not sure what the intended error rate was :)

I will close this now. Thank you!
