### ISSUE TITLE
how to get the probability result of svm machines ??

### ISSUE THREAD

**Issue by hwang-happy** [Shark-ML/Shark#153]
Dear Shark Community,
 
    shark::GaussianRbfKernel<> kernel(gama,false);
    shark::KernelClassifier<shark::RealVector> kc;
    shark::CSvmTrainer<shark::RealVector> trainer(&kernel,c,bias,false);
    trainer.train(kc,dat_train);
    shark::Data<unsigned int> pre=kc(dat_pre.inputs());

Just as the code above, the result of the machine is the predicted label.
But, how can i get the probability of each class? thank you very much !

**Comment by Ulfgard** [comment]
Hi,

the SVM is no probabilistic model. There is no valid way to obtain class probabilities (except fitting a sigmoid to the output of kc.decisionFunction(dat_pre.inputs()) as an approximation)

Best,
Oswin
________________________________

**Comment by hwang-happy** [comment]
thank you for reply!
Is the return of kc.decisionFunction(dat_pre.inputs())  a shark::Data<shark::Realvector> type ? thank you ?

**Comment by hwang-happy** [comment]
thank you for reply!
Is the return of kc.decisionFunction(dat_pre.inputs()) a shark::Data\<shark::Realvector\> type ? thank you ?

**Comment by hwang-happy** [comment]
Dear Shark Community,       

        GaussianRbfKernel<> kernel(gamma); 
	KernelClassifier<RealVector> kc;
	CSvmTrainer<RealVector> trainer(&kernel, C, bias);
	trainer.train(kc, data);
	
	Data<RealVector> out1=kc.decisionFunction(data.inputs());
	std::cout<<out1<<std::endl;

with error message below:
/home/hwang/try/shark/nosy_antoencode.cpp: In function ‘int main(int, char**)’:
/home/hwang/try/shark/nosy_antoencode.cpp:43:57: error: no matching function for call to ‘shark::KernelClassifier<shark::blas::vector<double> >::decisionFunction(shark::LabeledData<shark::blas::vector<double>, unsigned int>::InputContainer&)’
  Data<RealVector> out1=kc.decisionFunction(data.inputs());
                                                         ^
In file included from /home/hwang/softwear/Programe/libc++/shark/include/shark/Models/Kernels/KernelExpansion.h:44:0,
                 from /home/hwang/softwear/Programe/libc++/shark/include/shark/Algorithms/Trainers/AbstractSvmTrainer.h:52,
                 from /home/hwang/softwear/Programe/libc++/shark/include/shark/Algorithms/Trainers/CSvmTrainer.h:5,
                 from /home/hwang/try/shark/nosy_antoencode.cpp:11:
/home/hwang/softwear/Programe/libc++/shark/include/shark/Models/Converter.h:198:15: note: candidate: const Model& shark::ArgMaxConverter<Model>::decisionFunction() const [with Model = shark::KernelExpansion<shark::blas::vector<double> >]
  Model const& decisionFunction()const{
               ^
/home/hwang/softwear/Programe/libc++/shark/include/shark/Models/Converter.h:198:15: note:   candidate expects 0 arguments, 1 provided
/home/hwang/softwear/Programe/libc++/shark/include/shark/Models/Converter.h:203:9: note: candidate: Model& shark::ArgMaxConverter<Model>::decisionFunction() [with Model = shark::KernelExpansion<shark::blas::vector<double> >]
  Model& decisionFunction(){
         ^
/home/hwang/softwear/Programe/libc++/shark/include/shark/Models/Converter.h:203:9: note:   candidate expects 0 arguments, 1 provided
make[2]: *** [CMakeFiles/OneDragon.dir/nosy_antoencode.cpp.o] Error 1
make[1]: *** [CMakeFiles/OneDragon.dir/all] Error 2
make: *** [all] Error 2


how can i slove this problem?? thank you very much ~~

**Comment by Ulfgard** [comment]
I forgot a paranthesis:

kc.decisionFunction()(dat_pre.inputs())
________________________________
