### ISSUE TITLE
push_back elements to sparse dataset

### ISSUE THREAD

**Issue by smsaqaadj** [Shark-ML/Shark#155]
Hi, 
how can i push back element from one data set to another
the original dataset is:
shark::LabeledData<shark::CompressedRealVector, unsigned int> sparseTrainDataset;
and the resultant dataset should have some but not all the elements of the original training set, and at each cycle i might only get one element, so the main idea to push the new element to this resultant dataset.
the resultant dataset is also:
shark::LabeledData<shark::CompressedRealVector, unsigned int> resultantDataset;
my goal is to do the following:
resultantDataset.push_back(sparseTrainDataset.element(i));

the error after compiling: 

_/usr/local/include/shark/Data/Dataset.h:686:19: No member named 'inputs' in 'shark::PairReference<shark::DataBatchPair<shark::blas::compressed_matrix<double, unsigned long>, shark::blas::vector<unsigned int> >, boost::indirect_iterator<std::__1::__wrap_iter<const boost::shared_ptr<shark::blas::compressed_matrix<double, unsigned long> > *>, const shark::blas::compressed_matrix<double, unsigned long>, boost::use_default, const shark::blas::compressed_matrix<double, unsigned long> &, boost::use_default>, boost::indirect_iterator<std::__1::__wrap_iter<const boost::shared_ptr<shark::blas::vector<unsigned int> > *>, const shark::blas::vector<unsigned int>, boost::use_default, const shark::blas::vector<unsigned int> &, boost::use_default> >::type'_

your help is greatly appreciated!
Best Regards,

**Comment by Ulfgard** [comment]
Hi,

could you update to the latest git commit? I have no idea which version you are using but it could well be that this error is already fixed on master.
________________________________

**Comment by smsaqaadj** [comment]
Hi again, 

the commit version is up-to-date, please see this:
commit c6f63129 (HEAD -> master, origin/master, origin/HEAD)
Merge: 26738d32 7dd20ce2
Author: Oswin Krause <oswin.krause@di.ku.dk>
Date:   Mon Mar 6 16:35:26 2017

    Merge pull request #154 from egomeh/master

    Change name of result variable in end of Socket constructor

**Comment by Ulfgard** [comment]
Hi,

The reason i said is, that line 686 in Dataset.h is a comment:
https://github.com/Shark-ML/Shark/blob/master/include/shark/Data/Dataset.h#L686

________________________________
