### ISSUE TITLE
Link errors

### ISSUE THREAD

**Issue by sgondala** [Shark-ML/Shark#160]
I am using Visual studio 2013 and I have built shark using that. When I am trying to run a shark program, I am getting errors like - 

`Error	1	error LNK2019: unresolved external symbol "void __cdecl shark::csvStringToData(class shark::LabeledData<class shark::blas::vector<double>,unsigned int> &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum shark::LabelPosition,char,char,unsigned int)" (?csvStringToData@shark@@YAXAAV?$LabeledData@V?$vector@N@blas@shark@@I@1@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4LabelPosition@1@DDI@Z) referenced in function "void __cdecl shark::importCSV<double>(class shark::LabeledData<class shark::blas::vector<double>,unsigned int> &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,enum shark::LabelPosition,char,char,unsigned int)" (??$importCSV@N@shark@@YAXAAV?$LabeledData@V?$vector@N@blas@shark@@I@0@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4LabelPosition@0@DDI@Z)	c:\Users\sgondala\documents\visual studio 2013\Projects\ConsoleApplication2\ConsoleApplication2\ConsoleApplication2.obj	ConsoleApplication2

I have included Shark include in include directories. I have also included shark build libs in Linker -> General -> Additional Library Dependencies C:\Users\sgondala\Downloads\Shark-3.0.0\build\lib
`

**Comment by Ulfgard** [comment]
This is not running a program but compiling it. Does this error appear in your own compiled programs or compiling one of the shark programs, e.g. an example?

Best,
Oswin
________________________________

**Comment by sgondala** [comment]
I am compiling one of the example provided. I tried compiling 2-3 examples but everything resulted in these kinds of errors. I think I did not set some linker dependencies right. I am new to Visual Studio actually.

**Comment by Ulfgard** [comment]
So what exactly are you trying to do:

1. you are using the shark project generated by cmake and try to compile one of the examples
2. you are creating your own project based on an example

In the second case i would advise you to start off from the example given in

examples/ExampleProject/

There is a CMakeLists.txt which works given the right Shark_DIR path.
________________________________

**Comment by sgondala** [comment]
I am new to shark and want to try it out. So I did these 

1. Downloaded and installed boost libraries for Visual Studio 2013
2. Downloaded shark.zip, ran cmake. 

At this point, I have finished all the steps in [here](http://image.diku.dk/shark/sphinx_pages/build/html/rest_sources/getting_started/installation.html#windows-and-visual-studio) 

Now, I want to generate precompiled shark libraries for future use in projects. So I opened the .sln file that cmake generated in visual studio and built the solution. Now I have precompiled libraries in lib folder.

Error causing step: Now I want to use shark in some project of my own. For this, I have created a new visual studio project, wrote some code that uses shark and I want to compile this using precompiled shark libraries. At this point, when I am trying to build this solution, I am getting the above linking errors. How to solve this? 

The official shark website only has installation steps but no steps that describe using it in visual studio.

**Comment by Ulfgard** [comment]
you have to add the shark library to your linking options and the shark include paths to your include options.
________________________________

**Comment by sgondala** [comment]
I think the issue is something else. Let's do this step by step. 

As per "Installing Shark", after clicking "Generate" in CMake GUI, I got a shark.sln. 
Now to generate the libs, I need to build it in Visual Studio right!

I want 64 bit libs. So I opened .sln file in Visual studio, right click on Solution 'shark' (240 projects) -> Configuration Properties -> Configuration  and changed the platform to x64 (Selected copy settings from 32 bit)

Now I build the solution. I am getting the following errors  - 

error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'	C:\Users\sgondala\Downloads\Shark-3.0.0\build\src\shark.dir\Debug\CARTTrainer.obj

And many errors of the form - 
error LNK1104: cannot open file '..\lib\Debug\shark_debug.lib'	C:\Users\sgondala\Downloads\Shark-3.0.0\build\examples\LINK

Does shark not support 64bit?

**Comment by Ulfgard** [comment]
Hi,

what worked for me was to select the 64bit compiler as cmake generator.

I am not sure whether "select copy settings from 32 bit" is the right case here".
________________________________

**Comment by sgondala** [comment]
Yes, that's the mistake I was making. Thanks.

**Comment by amaad** [comment]
@sgondala  can you please tell me how you resolve that problem ??  LNK1104	cannot open file '..\lib\Debug\shark_debug.lib'

**Comment by sgondala** [comment]
It's beena long time and so my memeory is a bit hazy here. I think the issue was with 64 bit vs 32 bit. Make sure at all the steps you keep 64 bit only.

**Comment by amaad** [comment]
my cMake version is 3.9.0 and boost version is 1_59_0 and shark version is 3.0.0 and VS2015 , windows 10 64 bit

**Comment by amaad** [comment]
i want to build boost and shark machine learning library. link them
together with my code in the visual studio 2015.
