### ISSUE TITLE
error LNK2019 

### ISSUE THREAD

**Issue by arthur-leguennec** [Shark-ML/Shark#161]
Hi,
I using Visual Studio 2013 on Windows 10, and after to build Shark with Cmake and VS 2012 without error, I decided to use Shark in other project and I have these errors : 

`Error	23	error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl shark::RFTrainer::RFTrainer(bool,bool)" (__imp_??0RFTrainer@shark@@QEAA@_N0@Z) referenced in function "public: void __cdecl RandomForestTrainer::train(double,class std::vector<class std::vector<float,class std::allocator<float> >,class std::allocator<class std::vector<float,class std::allocator<float> > > > const &,class std::vector<unsigned int,class std::allocator<unsigned int> > const &)" (?train@RandomForestTrainer@@QEAAXNAEBV?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEBV?$vector@IV?$allocator@I@std@@@3@@Z)	D:\Arthur Le Guennec\Documents\trunk-master\cloudcompare\build_msvc2013_64bits\plugins\qCanupo\qCanupoTools.obj	QCANUPO_PLUGIN_DLL`

`Error	24	error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual void __cdecl shark::RFTrainer::train(class shark::RFClassifier &,class shark::LabeledData<class shark::blas::vector<double>,unsigned int> const &)" (__imp_?train@RFTrainer@shark@@UEAAXAEAVRFClassifier@2@AEBV?$LabeledData@V?$vector@N@blas@shark@@I@2@@Z) referenced in function "public: void __cdecl RandomForestTrainer::train(double,class std::vector<class std::vector<float,class std::allocator<float> >,class std::allocator<class std::vector<float,class std::allocator<float> > > > const &,class std::vector<unsigned int,class std::allocator<unsigned int> > const &)" (?train@RandomForestTrainer@@QEAAXNAEBV?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEBV?$vector@IV?$allocator@I@std@@@3@@Z)	D:\Arthur Le Guennec\Documents\trunk-master\cloudcompare\build_msvc2013_64bits\plugins\qCanupo\qCanupoTools.obj	QCANUPO_PLUGIN_DLL`

`Error	25	error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl shark::RFTrainer::setOOBratio(double)" (__imp_?setOOBratio@RFTrainer@shark@@QEAAXN@Z) referenced in function "public: void __cdecl RandomForestTrainer::train(double,class std::vector<class std::vector<float,class std::allocator<float> >,class std::allocator<class std::vector<float,class std::allocator<float> > > > const &,class std::vector<unsigned int,class std::allocator<unsigned int> > const &)" (?train@RandomForestTrainer@@QEAAXNAEBV?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEBV?$vector@IV?$allocator@I@std@@@3@@Z)	D:\Arthur Le Guennec\Documents\trunk-master\cloudcompare\build_msvc2013_64bits\plugins\qCanupo\qCanupoTools.obj	QCANUPO_PLUGIN_DLL`

`Error	26	error LNK1120: 3 unresolved externals	D:\Arthur Le Guennec\Documents\trunk-master\cloudcompare\build_msvc2013_64bits\plugins\qCanupo\Debug\QCANUPO_PLUGIN_DLLd.dll	1	1	QCANUPO_PLUGIN_DLL
`

So I understand the last one error (:-)) but I don't know how resolve the others.
In my CMake configuration, I have Shark_DIR = "D:/Devs/Libraries/Shark-3.1.3/build_msvc2013_64bits"

**Comment by arthur-leguennec** [comment]
I forget to precise, I'm using Shark 3.1.3, because I used Shark 3.0.0 and after to look for a solution, I found this [topic ](https://github.com/Shark-ML/Shark/issues/10) and I thought this would resolve my problem.

**Comment by Ulfgard** [comment]
Can I see your CMakeLists.txt?
________________________________

**Comment by arthur-leguennec** [comment]
of Shark or of my project ?

**Comment by arthur-leguennec** [comment]
My CmakeLists.txt of Shark
[CMakeLists.txt](https://github.com/Shark-ML/Shark/files/841530/CMakeLists.txt)

**Comment by Ulfgard** [comment]
I meant the one you are using for your own project.

Best,
Oswin
________________________________

**Comment by arthur-leguennec** [comment]
ok sorry, here it is :
[CMakeLists.txt](https://github.com/Shark-ML/Shark/files/841548/CMakeLists.txt)

**Comment by Ulfgard** [comment]
I still do not see which targets you are building as the targets in the file are commented out. I would guess you have forgotten to add shark as a library to link to as is done in our example file in examples/ExampleProject:

add_executable(ExampleProject HelloWorld.cpp)
target_link_libraries(ExampleProject ${SHARK_LIBRARIES})
________________________________

**Comment by arthur-leguennec** [comment]
ok, I did this :

    find_package(Shark REQUIRED)
    include(${SHARK_USE_FILE})
    # Executable
    target_link_libraries(QCANUPO_PLUGIN_DLL ${SHARK_LIBRARIES})

But when I configure my project with CMake, I have this error : 

    CMake Error at plugins/qCanupo/CMakeLists.txt:22 (target_link_libraries):
    Cannot specify link libraries for target "QCANUPO_PLUGIN_DLL" which is not
    built by this project.

I put `D:/Devs/Libraries/Shark-3.1.3/build_msvc2013_64bits` in Shark_DIR.

**Comment by Ulfgard** [comment]
You can not add libraries to a target that you have not defined yet. See my example: i first added the executable and then added the libraries to link to that target.

________________________________

**Comment by arthur-leguennec** [comment]
Yes, but I don't need an executable, I want just add Shark for one plugin in the software. Normally, after building my project, I just generate a DLL (of my project) for the software.

**Comment by Ulfgard** [comment]
so the shark dll/lib is going to be a dependency of that plugin
________________________________

**Comment by arthur-leguennec** [comment]
yes, so after other tests, my error was I added `include( ../CMakePluginTpl.cmake )` after, and not before as requested (according the creator of software) and `target_link_libraries(${PROJECT_NAME} ${SHARK_LIBRARIES})` works now. I have other problems but not the subject of this topic (nor of Shark). 
I close the topic.
Thank you for your help and your time @Ulfgard !
