### ISSUE TITLE
Loading saved RFClassifier takes time

### ISSUE THREAD

**Issue by nishantkapur** [Shark-ML/Shark#163]
Hi,
I have trained a Random Forest Classifier and saved it by using boost::archive::polymorphic_text_oarchive. 
Everything is fine. The model was saved correctly and it also loads correctly. The issue is that the classifier saved is of size roughly 700 mb as my dataset was huge and takes around 40-45 seconds just to load the classifer in the code. Is there a way to minimize this loading time? 

Following the way I am loading the trained classifier

```
ifstream ifs("model.xml");
boost::archive::polymorphic_text_iarchive ia(ifs);
model_test.read(ia);
ifs.close();
```

Thanks

**Comment by Ulfgard** [comment]
Hi,

you could try saving and restoring it using a polymorphic_binary_oarchive and  polymorphic_binary_iarchive.

Best,
Oswin
________________________________

**Comment by nishantkapur** [comment]
I tried using polymorphic_binary_oarchive  and polymorphic_binary_iarchive. I am able to save the RFClassifier but somhow i get an exception when i am restoring it. 

> 
> First-chance exception at 0x00007FFCC7107788 in RFTutorial.exe: Microsoft C++ exception: boost::archive::archive_exception at memory location 0x000000623479F550.
> Unhandled exception at at 0x00007FFCC7107788 in RFTutorial.exe: Microsoft C++ exception: boost::archive::archive_exception at memory location 0x000000623479F550.

I am not much familiar with boost. Following is the code for read and write. I dont know if i am doing anything wrong
```
ofstream ofsBin("model.xml");
boost::archive::polymorphic_binary_oarchive oaBin(ofsBin);
model.write(oaBin);
ofsBin.close();

RFClassifier model_BIN;
  
ifstream ifsBin("model.xml");
boost::archive::polymorphic_binary_iarchive iaBin(ifsBin);
model_BIN.read(iaBin);
ifsBin.close();

**Comment by Ulfgard** [comment]
Hi,

you have to open your files with the binary flag:


std::ifstream ifs("filename", std::ios::binary);
std::ifstream ofs("filename", std::ios::binary);

________________________________

**Comment by nishantkapur** [comment]
It works now!!! Thanks!!! Time taken for restoring the classifier dropped down to 3.5 seconds from 45 seconds. I was wondering if there is any way to embed the classifier parameters in the code rather than loading the file. Would that be faster?

**Comment by Ulfgard** [comment]
Hi, 

good that this could resolve most of your issue. While your suggestion could make running times faster(but not by so much), it would complicate matters a lot as you would need to find a way how to embed the parameters and structure into your executable.

I will close this as fixed, but feel free to comment if there is further need for discussion.
