### ISSUE TITLE
importCSV problem parsing file

### ISSUE THREAD

**Issue by notarbar** [Shark-ML/Shark#164]
testing the example provided in the tutorial http://image.diku.dk/shark/sphinx_pages/build/html/rest_sources/tutorials/algorithms/rf.html
the example compiles but fails to run throwing an error 
"terminate called after throwing an instance of 'shark::Exception'
  what():  [import_csv_reader_points] problems parsing file (3)"

Toolchain:CMake, g++

**Comment by Ulfgard** [comment]
when you run the program, is in the working directory a data/C.csv file? it should be in your build directory
________________________________

**Comment by notarbar** [comment]
My Bad the importCSV takes the full path to the csv file .
Thanks for this fast support man :+1:  :100:
