### ISSUE TITLE
Good way to create a dataset

### ISSUE THREAD

**Issue by arthur-leguennec** [Shark-ML/Shark#166]
Hi,
in the examples of the site, the creation of dataset pass by the import of the data of CSV (see RFT). But I don't find examples with a data that be stocked in a `std::vector<std::vector<float>>`. Here, I wrote a example to represent my problem:

    void train(double ratio, const std::vector<std::vector<float>>& samples, const std::vector<unsigned int>& labels)
	{
		Data<RealVector> inputs;
		Data<unsigned int> outputs;

                /*
               Here, the code I would like to full the variables inputs and outputs (labels)
               */

		ClassificationDataset data(inputs, outputs);
		data.shuffle();
		data.makeIndependent();
		RFTrainer trainer(); // first true: compute feature importance; second true: compute OOB error
		RFClassifier model;
		trainer.train(model, data);
	}

**Comment by Ulfgard** [comment]
Hi,

The easiest is not to start from vector<vector<float> > but possible from vector<RealVector> for your samples. In this case you can create a dataset simply by

ClassificationDataset data = createLabeledDataFromRange(samples,labels);

For this changing the type should already be sufficient. If this is not possible the easiest is still probably to convert the vector...

Best,
Oswin


________________________________

**Comment by arthur-leguennec** [comment]
The type of `samples` can't change, but if I create a variables like this `std::vector<RealVector> inputs(samples.size());` and `UIntVector output(samples.size())` and I do this : 

    for (std::size_t i = 0; i < samples.size(); i++) {
        for (std::size_t j = 0; j < samples.at(0).size(); j++) {
            inputs.at(i)(j) = static_cast<double>(samples.at(i).at(j));
        }
        outputs(i) = labels.at(i);
    }
    ClassificationDataset data = createLabeledDataFromRange(inputs, outputs);

It's ok like this .?

**Comment by Ulfgard** [comment]
Hi,

this should be fine!
________________________________

**Comment by Ulfgard** [comment]
the labels are already the right type, they do not need to be changes.
________________________________

**Comment by arthur-leguennec** [comment]
ok thanks a lot! I close this issue
