### ISSUE TITLE
c++11 incompatibility between shark::size and std::size

### ISSUE THREAD

**Issue by Ulfgard** [Shark-ML/Shark#17]
from the mailing list

"Compiling shark with VS14 and boost 1.59 I get an error "'shark::size' ambiguous call to overloaded function". The ambiguity is between std::size and shark::size, and in the affected files both "using namespace std" and "using namespace shark" are defined. Adding namespace shark to size() solves the problem, but it would be nice to not have to manually do this. "

shark::size got introduced because at that date, std::size was not available. As shark does not officially support C++11 yet, we can defer the fix until its time

**Comment by TGlas** [comment]
Okay, now we finally switched to C++11. Is shark::size already removed, i.e., can we close this issue?
