### ISSUE TITLE
No usable CBLAS Library found. No fast linear Algebra used.

### ISSUE THREAD

**Issue by vincferr** [Shark-ML/Shark#182]
Hi,

I was able so far to follow the install guide (Windows 7, Visual studio). Thank you very much, it is very clear!
As I am concerned about speed, I see that I have in cmake the warning:

No usable CBLAS Library found. No fast linear Algebra used.

How do I fix this? Which library can I use that will provide the needed libraries? Thanks
Enzo

**Comment by Ulfgard** [comment]
sorry for the late reply, this kind of vanished from my sight. on windows you have very limited options.

OpenBLAS is more or less the only "out-of-the-box" solution that works:

https://github.com/xianyi/OpenBLAS
