### ISSUE TITLE
Front creation in the new hypSSP 2d algorithm

### ISSUE THREAD

**Issue by bgz38** [Shark-ML/Shark#189]
I am puzzled by the function createFront  from the hypSSP algorithm in dimension 2:

https://github.com/Shark-ML/Shark/blob/master/include/shark/Algorithms/DirectSearch/Operators/Hypervolume/HypervolumeSubsetSelection2D.h

Function createFront applies at line 238 std::unique with a lambda that is not an equivalence relation.
As a result I think it's behaviour is undefined and in particular it may remove points that are not dominated.
Am I missing something?

**Comment by Ulfgard** [comment]
Hi,

I See. I think you are playing here on the missing symmetry, right? We currently assume that elements which come "earlier" in the sequence are always the first argument. So we should use instead:

auto newEnd = std::unique(front.begin(),front.end(),[](Point const& x, Point const& y){
    if(y.f1 >= x.f1)//y dominated or equal to x in first coordinate
        return y.f2 >= x.f2;//y dominated or equal to x in second coordinate
    return x.f2 >= y.f2;//x dominated by y
});

now the equivalence relation should be "one point dominates the other or they are the same". The first lexicographic sort then will introduce the necessary order so that the first version kept is actually the one that dominates the other.

Agreed?

Best,
Oswin

**Comment by bgz38** [comment]
in fact what you propose is not yet an equivalence relation: it is symmetric all right, but not transitive : having (p dominate q  AND p' dominates q) tells you nothing about the relation between p and p'.
I think std::unique is not the right tool here. Perhaps you had better use the classical /trivial skyline algorithm:
in short: sort points on f1  then traverse the vector by decreasing order, record the maximal f2 and push_back when the point is not dominated.
 (in fact, if you don't want to pop when a larger f2 is encountered, you should actually sort on lexicographic order (f1, f2))

**Comment by Ulfgard** [comment]
Hi,

I am not sure what you are saying here. Your example does not show transitivity but it could be a typo:
(p dominates q AND p' dominates q) => (p dominates p' AND p' dominates q).  This is indeed not an equivalence relation. but adding equality is. as p dominates or equals p' it is at least as good or equal to the function values of p' therefore as q does not have any better function values than p' it will be dominated by p or is equal. in both cases we would like to remove them.

________________________________

**Comment by bgz38** [comment]
perhaps we could skype? I checked my comment and there is no typo: I am saying that 'dominance is not transitive' and therefore your relation mixing dominance and equality is not an equivalence relation.

**Comment by Ulfgard** [comment]
Hi,

see:

https://books.google.dk/books?id=OSTn4GSy2uQC&pg=PA30&lpg=PA30&dq=dominance+transitive&source=bl&ots=tEowjyIrc0&sig=eaOg2FKeh_ZcsCdpLwF4HHf4c90&hl=en&sa=X&ved=0ahUKEwj2i6Cdic_UAhVqLZoKHQkjCasQ6AEIYTAJ#v=onepage&q=dominance%20transitive&f=false
________________________________

**Comment by bgz38** [comment]
Perhaps we should skype ?
yes, sry, dominance is indeed transitive, that's why I deleted immediately a post. 
But I am quite sure you will not be able to use std::unique. 
My argument is: take 3 points with
 (p dominate q AND p' dominates q)  -- no typo there.
You want to remove q. So you would make q equivalent to p and p' in your relation.
But then p and p' are equivalent and you keep only one of them. Which is incorrect; you don't know until you compare them.

**Comment by bgz38** [comment]
And because an example may help: 
p=(2,1)
p'=(1,2)
q=(0,0) -- for a maximization front, or (3,3) for minimization
With the symmetric relation R you propose we have 
R(p,q) -- because p dominates q
R(p',q) -- because p'dominates q
but we don't have R(p,p') so R is not an equivalence relation

**Comment by Ulfgard** [comment]
i see the issue now. i will create a fix
