### ISSUE TITLE
Model Serialization to a HDF5 file

### ISSUE THREAD

**Issue by skn123** [Shark-ML/Shark#19]
Can we have an option to do the following:
a.) Serialze the model into a string 
b.) Convert the string into a char array
c.) Save the char array into a HDF5 file given that we can optionally build hdf5 into shark?

**Comment by Ulfgard** [comment]
a) and b) is already possible:
    
        std::ostringstream outputStream;  
        shark::TextOutArchive oa(outputStream);  
        oa << model;//serialize model
        char const* char_array = outputStream.str().c_str();

c) is not implemented

the easier solution is to have a hdf5 archive class for boost::Serialization and i think this already exists. But for now implementing or shipping it is out of scope.

**Comment by skn123** [comment]
How would I do the reverse? i.e., convert a string array to a model?

**Comment by skn123** [comment]
Hi Ulfgard any thoughts on how to do the last step?

**Comment by Ulfgard** [comment]
No, I have not really looked into it. I guess there should be a simple HDF5 API call doing this, but I am no HDF5 expert, sorry.

**Comment by skn123** [comment]
Ulfgard, I can do the whole chain; All I was looking for was this step:
a.) Given a char array how can I convert the char array into a Shark Model?

**Comment by Ulfgard** [comment]
a) is almost the same as a) i mentioned earlier:
    
    std::string yourdata;
    std::istringstream inputStream(yourdata);  
    shark::TextInArchive ia(inputStream);  
    is >> model;

**Comment by skn123** [comment]
Now, If I would like to add this as a function, where would I go about adding this? Can you please correct the snippet; It should be 
ia >>model

**Comment by skn123** [comment]
I am closing this thread..
