### ISSUE TITLE
Where do i suppose to find the input file?   faithful.csv

### ISSUE THREAD

**Issue by jiawenhao2015** [Shark-ML/Shark#190]
I find that   /examples/Unsupervised/**KMeansTutorial.cpp** needs an input file,**faithful.csv**.

and the comment says  **"k-means Clustering Tutorial Sample Code, requires the data "**

but i don't find the faithful.csv in the path or any file folder,do i miss some files?
many thanks!!!

**Comment by Ulfgard** [comment]
Hi, 

the data is in examples/Unsupervised/data, see https://github.com/Shark-ML/Shark/tree/master/examples/Unsupervised/data

I hope this solves your problem :)

**Comment by jiawenhao2015** [comment]
yeah！i find it!  thanks a lot!  many many thanks~
