### ISSUE TITLE
Wrong SIZE_CHECK in Normalizer model

### ISSUE THREAD

**Issue by bjornbugge** [Shark-ML/Shark#192]
When building the elmTutorial.cpp example with debugging enabled, it blows up due to a failed assertion in Normalizer.h:194: `SIZE_CHECK(input.size1() == m_A.size())`. 
I think the correct check would be `SIZE_CHECK(input.size2() == m_A.size())` instead.

**Comment by Ulfgard** [comment]
Tak!
