### ISSUE TITLE
Fails to build with gcc 7

### ISSUE THREAD

**Issue by ghisvail** [Shark-ML/Shark#194]
Forwarded from the Debian bug tracker:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853658

The package fails to build in a test rebuild on at least amd64 with gcc-7/g++-7, but succeeds to build with gcc-6/g++-6. The severity of the issue has been raised to RC since gcc-7 is now the default toolchain on Debian unstable. A copy of the complete build log is available in the original bug report.

There are multiple errors of the form:
```
In file included from /<<BUILDDIR>>/shark-3.1.3+ds1/include/shark/Rng/GlobalRng.h:90:0,
                 from /<<BUILDDIR>>/shark-3.1.3+ds1/include/shark/Core/utility/functional.h:41,
                 from /<<BUILDDIR>>/shark-3.1.3+ds1/include/shark/Data/Dataset.h:54,
                 from /<<BUILDDIR>>/shark-3.1.3+ds1/include/shark/Algorithms/KMeans.h:40,
                 from /<<BUILDDIR>>/shark-3.1.3+ds1/src/Algorithms/KMeans.cpp:36:
/<<BUILDDIR>>/shark-3.1.3+ds1/include/shark/Rng/Dirichlet.h: In function 'std::basic_ostream<_Ch, _Up>& shark::operator<<(std::basic_ostream<_Ch, _Up>&, const shark::Dirichlet_distribution<RealType>&)':
/<<BUILDDIR>>/shark-3.1.3+ds1/include/shark/Rng/Dirichlet.h:96:12: error: invalid use of member function 'const std::vector<_Tp>& shark::Dirichlet_distribution<RealType>::alphas() const' (did you forget the '()' ?)
    os << d.alphas.size();
```

**Comment by LocutusOfBorg** [comment]
hello, ping?

**Comment by LocutusOfBorg** [comment]
@ghisvail that Rng code has been removed in the current git master, how do you feel about packaging a snapshot?

**Comment by ghisvail** [comment]
@LocutusOfBorg sure, though I'd like an acknowledgement from upstream that they are ok with Debian shipping a snapshot version.

**Comment by LocutusOfBorg** [comment]
I'm not even sure if it builds or not :)

**Comment by Ulfgard** [comment]
Hi,

sorry, i have been a week on a summer school with not much stable wifi. 

Development builds and works, but i would rather fix the bug on monday as development is in some weird intermediate state and docs are not completely up to date. My fix is most likely just removing that file.

**Comment by Ulfgard** [comment]
v3.1.4 should fix our issue here
