### ISSUE TITLE
How do you get the predicted results

### ISSUE THREAD

**Issue by alq115** [Shark-ML/Shark#197]
I want to put a single data item into a training program and get the predicted results, how to do it.For example:

        trainer.train(model, traindata);
        Data<RealVector> prediction = model(testdata.inputs());
        ZeroOneLoss<RealVector> loss;
        double error_rate = loss(testdata.labels(), prediction);

But how do you get the ‘prediction’ results

**Comment by Ulfgard** [comment]
Hi,

there are different ways. for example:

for(auto elem:prediction.elements()){
    std::cout<<elem<<std::endl;//your prediction
}
________________________________

**Comment by alq115** [comment]
Hi,
for(auto elem:prediction.elements()){
    std::cout<<elem<<std::endl;//your prediction
}

  I want to show elem in messagebox functions.But I don't know the data type of elem. Can you help me

**Comment by Ulfgard** [comment]
Hi,

the exact type is an implementation detail. However, you can simply use the type that you defined in your dataset (RealVector).

for(RealVector elem:prediction.elements()){//note the copy.
std::cout<<elem<<std::endl;//your prediction
}


________________________________
