### ISSUE TITLE
Cannot find *.cpp file in the Shark project created by CMake 

### ISSUE THREAD

**Issue by SPEAQ** [Shark-ML/Shark#199]
Hi
 Now i tried to configure Shark in Visual Studio 2013 on Windows 7 platform by CMake 3.9.3 GUI.
The report of CMake said that the Shark was generated successfully like this: 
**********************************************
The C compiler identification is MSVC 18.0.40629.0
The CXX compiler identification is MSVC 18.0.40629.0
Check for working C compiler: D:/software_set/vs2013/VC/bin/x86_amd64/cl.exe
Check for working C compiler: D:/software_set/vs2013/VC/bin/x86_amd64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: D:/software_set/vs2013/VC/bin/x86_amd64/cl.exe
Check for working CXX compiler: D:/software_set/vs2013/VC/bin/x86_amd64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Will build: Release
Boost version: 1.57.0
Found the following Boost libraries:
  serialization
  filesystem
  system
Using boost from 
OpenMP found
Checking HDF5 installation:HDF5 package might be broken.
  C Compiler Extension not found.
  CXX Compiler Extension not found.
Disabling HDF5.
No usable CBLAS Library found. No fast linear Algebra used.
Boost version: 1.57.0
Found the following Boost libraries:
  unit_test_framework
Configuring done
Generating done
*******************************************
And it also creat a shark.sln file in the destination directory. But I cannot find any *.cpp file of the example project like this:
![image](https://user-images.githubusercontent.com/17939187/30778855-7916b938-a112-11e7-972b-328a863eaafe.png)

Anyone has encounted the same question and know how to resolved it ? Thanks!

**Comment by Ulfgard** [comment]
Hi,

the cpp files do actually not exist until you try building the project. The original source files are the .tpp files which also contain information for including snippets into the documentation. So try building the project and then you should be able to access the cpp

**Comment by SPEAQ** [comment]
Hi,
 OK,Thanks. I tried to build the random forest example, but get another problem. I will creat a new issue about that.
