### ISSUE TITLE
error C2893: Failed to specialize function template 'unknown-type shark::getBatchElement(const BatchT &,size_t)

### ISSUE THREAD

**Issue by SPEAQ** [Shark-ML/Shark#200]
Hello,

Now I am trying to build example "RFTutorial" of Shark 3.1 in Visual Studio 2013 on Windows 7 platform. However, I get a error that I cannot deal with.

The error message is :
 "\include\shark\data\Impl/Dataset.inl(758): error C2893: Failed to specialize function template 'unknown-type shark::getBatchElement(const BatchT &,size_t)"
The code in "include\shark\data\Impl/Dataset.inl(758) is:
	typedef InputLabelPair<
		decltype(getBatchElement(std::declval<Batch1Type&>(), 0)),
		decltype(getBatchElement(std::declval<Batch2Type&>(), 0))
	> reference;
	typedef InputLabelPair<
		decltype(getBatchElement(std::declval<typename std::add_const<Batch1Type>::type&>(), 0)),
		decltype(getBatchElement(std::declval<typename std::add_const<Batch2Type>::type&>(), 0))
	> const_reference;
and the definition of  getBatchElement is:
template<class BatchT>
auto getBatchElement(BatchT& batch, std::size_t i)->decltype(BatchTraits<BatchT>::type::get(std::declval<BatchT&>(),i)){
	return BatchTraits<BatchT>::type::get(batch,i);
}

template<class BatchT>
auto getBatchElement(BatchT const& batch, std::size_t i)->decltype(BatchTraits<BatchT>::type::get(std::declval<BatchT const&>(),i)){
	return BatchTraits<BatchT>::type::get(batch,i);
}

I do not know why it is wrong. 
Anyone has encounted the same question and know how to resolved it ? Thanks!

**Comment by Ulfgard** [comment]
without the full and unredacted compiler error message it is impossible to figure out what is wrong. I suspect a compiler bug and i am not sure whether we even support msvc 12.

**Comment by SPEAQ** [comment]
Thanks, Now I know where is wrong. The auto in the defination of getBathElement is illegal in msvc12.
I will download the visual studio 2017 and try again.
