### ISSUE TITLE
Cannot run release *.exe file built by Shark project, error: missing *.DLL 

### ISSUE THREAD

**Issue by SPEAQ** [Shark-ML/Shark#201]
I am using Shark in Visual Studio 2017 on Windows 7 platform. When i build the example project"RFTutorial" to RFTutorial.exe and run it in another computer, but error occures："The program can not start because VCOMP140.dll is missing from your computer"
   I have changed the "Configuration Type" to "Application(.exe)"
![image](https://user-images.githubusercontent.com/17939187/31044133-19bc6cfa-a5fc-11e7-8e44-7ad104ba034a.png)
changed "Runtime Library" to "Multi-threaded(/MT)"
![image](https://user-images.githubusercontent.com/17939187/31044140-41896602-a5fc-11e7-8e62-e7ba57c5dd1c.png)

Is there any other place need to be changed to build a release exe?
Thanks!

**Comment by Ulfgard** [comment]
you of course need the proper microsoft runtime on another pc.

https://www.microsoft.com/en-ca/download/details.aspx?id=48145

this is not a shark issue as far as i can tell.
________________________________

**Comment by SPEAQ** [comment]
Hi, Ulfgard

I think this is about how to use Shark as a library into my code. As far as i know, if i compile Shark library into static library and build my application by static way( "\MT"), when runing the application, it will not use other runtime *.dlls anymore. 
You can see it in this : https://corecplusplustutorial.com/static-and-dynamic-library-cpp/ 
If I must install microsoft runtime dlls in another computer before running my application, it would be too troublesome. 
How can i use the Shark project as a library in my code? Can you give me any advice? Thanks.
