### ISSUE TITLE
Where is this file in Shark?

### ISSUE THREAD

**Issue by skn123** [Shark-ML/Shark#202]
I am trying to build OTB with Shark. However, Shark does not have this file. Any pointers?
https://www.orfeo-toolbox.org/doxygen/otbSharkRandomForestsMachineLearningModel_8txx.html

**Comment by Ulfgard** [comment]
Sorry for the very late reply!

You have unfortunately not specified which file is missing. It might be that they use one of our last releases. I think if it is Converter.h it should be changed by Classifier.h - but no guarantuees here. I close this.
