### ISSUE TITLE
INSTALL project build error

### ISSUE THREAD

**Issue by imamushroom** [Shark-ML/Shark#205]
When I'm building the INSTALL project after a successful ALL_BUILD build, I'm getting the following error:

`  -- Install configuration: "Debug"
  CMake Error at cmake_install.cmake:36 (file):
    file INSTALL cannot make directory "C:/Program Files
    (x86)/shark/include/shark//shark": No such file or directory
  
  
  -- Installing: C:/Program Files (x86)/shark/include/shark//shark
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 1.
`

My system is Win10 x64, Visual Studio 17 Community using shark 3.1.0, and the project type is set to Release (although the error relates to the Debug build and I do not understand why).

My cmake build options are given in the attached file.

![cmake](https://user-images.githubusercontent.com/7989372/32766875-21b60140-c911-11e7-8618-561865159b98.png)

**Comment by Ulfgard** [comment]
Hi,

I am no expert with Windows at all. Are you sure you have the right to install the library at the target location "C:/Program Files (x86)/shark"? Could you try installing it in your own home directory? 

otherwise, Shark does not need to be installed on your system. it lives fine in the directory where you built it.

**Comment by imamushroom** [comment]
Thanks for your reply.

You're absolutely correct, this was the problem. Probably, due to a rights issue under the Program Files directory. Maybe, the default should be amended to something more useful under Win10.

Thanks again.

**Comment by Ulfgard** [comment]
Glad you got it to work!

Thanks for the suggestion, but this is the cmake default (consistent with the system directories on linux and mac which alse require administrator rights).
