### ISSUE TITLE
New Random Forest implementation

### ISSUE THREAD

**Issue by inglada** [Shark-ML/Shark#206]
Hi,
I just noticed that there is a new RF implementation with some important API changes. I have succeded in adapting my simple examples with respect to the fact that the classifier is now templated. However, I don't understand what happened to the ArgMaxConverter class that I used to use to convert the RF votes into the decision.

Thanks.

**Comment by inglada** [comment]
Hi again,
Git allowed me to find that ArgMaxConverter was renamed to Classifier. I am still having trouble converting a simple example. I am building a classification data set as follows:
  ```

std::vector<RealVector> features;
std::vector<unsigned int> class_labels;
ClassificationDataset data =  createLabeledDataFromRange(features, class_labels);
```

After filling the data set, I split it into training and validation with this approach:

`ClassificationDataset dataTest = splitAtElement(data, initTrainSamplesRatio*totalNbSamples);
`

I declare my RF trainer and classifier:
```
RFTrainer<unsigned int> trainer;
RFClassifier<unsigned int> model;
```
Here I am not sure of what the template parameter is (label type, feature type?).

Then, train and predict:
```
trainer.train(model, data);
Data<RealVector> prediction = model(dataTest.inputs());
```


However, I get the following compilation error:

```
/home/inglada/Dev/RF-EM/src/rf-em.cxx:118:36: error: conversion from ‘shark::Data<unsigned int>’ to non-scalar type ‘shark::Data<remora::vector<double> >’ requested
Data<RealVector> prediction = model(dataTest.inputs());
                               ~~~~~^~~~~~~~~~~~~~~~~~~
```

I don't understand why the data type which is suited for training does not work for the prediction as it used to be the case with the previous version.
Thanks.

**Comment by Ulfgard** [comment]
Hi,

sorry, the docs on the webpage are not sufficiently updated to the master version, we are still in the process of updating it. The examples are up to date, though.

We adapted the random forest to follow the general shark convention for Trainers: the output type of a trained model should fit the LabelType during training. So if a random forest is trained on a classification problem, the output is unsigned int, for a regression problem it is RealVector. 

Therefore the correct evaluation is:
```
Data<unsigned int> prediction = model(dataTest.inputs());
ZeroOneLoss<> loss
double error = loss(dataTest.labels(),prediction)
```
This should be canonical for all Classification problems.

Be warned, we are still changing this class a little bit internally. It should not lead to any breakage of the code above but we strive to make it more canonical (e.g. we want to derive RandomForest<unsigned int> from Classifier<SomeModel> to have a canonical interface for classification across Shark)

If you manage to try it out, we would be happy to hear about your experiences with the new implementation.

**Comment by inglada** [comment]
Hi,

Thanks for your answer. 
Does that mean that we no longer have access to the vote count for each label?
I used to use 
`
Data<RealVector> prediction = model(dataTest.inputs());`

to estimate the probability of each label for each sample.
How can I do that now?
Thanks.

**Comment by Ulfgard** [comment]
Hi,

next Monday, decisionFunction is going to be implemented. Sorry to hear that you are struck by this!

________________________________

**Comment by inglada** [comment]
Thanks for the information. I am happy to give some feedback on this implementation. I have several uses for Shark's RF and I can tell how the new version behaves wrt the previous one.
Cheers.

**Comment by Ulfgard** [comment]
okay, you should be able to use this class exactly as a Classifier for classification, e.g. 

model.decisionFunction() should return the class-wise probabilities. Please tell me if something is still off.

**Comment by inglada** [comment]
Great! I could update one of my programs and everything seems OK. I will report back if there are any issues.
