### ISSUE TITLE
Segfault when using a RandomForest model saved in a file

### ISSUE THREAD

**Issue by inglada** [Shark-ML/Shark#208]
Hi,

I have been playing with the new implementation of the Random Forest classifier and I have problems when using a model that I have saved (serialized). I have prepared an example program and a data file which produces the issue. The programs exits witha segmentation fault.

The problem may be in the way I do the serialization, but this code worked without issues with the previous implementation of the RF classifier.

Thanks for your help.

Jordi

[rf-bug.zip](https://github.com/Shark-ML/Shark/files/1540261/rf-bug.zip)

**Comment by inglada** [comment]
Having a closer look at it, it seems that the problem comes indeed from the serialization. If I create the second model by copying the first one and then I load the file, there is no segfault:

 ```
 shark::RFClassifier<unsigned int> model2{model};
  LoadModel("/tmp/model", model2);

```
However, if I load a model trained on a previous run (the model will have the same meta-parameters, but different structure), I don't get a segfault, but an exception:

 ```
bug: [....]/include/shark/Models/MeanModel.h:60: void shark::MeanModel<ModelType>::doEval(const InputBatch&, shark::RealMatrix&, shark::MeanModel<ModelType>::tag<unsigned int>) const [with InputBatch = remora::matrix<double, remora::row_major>; ModelType = shark::CARTree<unsigned int>; shark::RealMatrix = remora::matrix<double, remora::row_major>]: Assertion `responses(p) < m_outputDim' failed.`
 ```

I hope this helps finding the bug.

Thanks.

**Comment by Ulfgard** [comment]
Thanks for reporting this. I am fixing it this weekend. I think we just miss a serialisation test here...
________________________________

**Comment by inglada** [comment]
Hi,
Any progress? Is there anything I can do to help?
Thanks.

**Comment by Ulfgard** [comment]
should be fixed now. A serialization routine did not get ported.

Don't hesitate to reopen if it is still amiss!
