### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by ghisvail** [Shark-ML/Shark#21]
Dear Shark developers,

I am trying to revive the effort of submitting a package for Shark to the Debian archive. There has been an ITP filed [here](https://lists.debian.org/debian-devel/2015/02/msg00012.html) at the beginning of the year, but activity seems to have ceased.

I am aware that you guys already already have a [debianization](https://github.com/Shark-ML/Shark/tree/master/debian) upstream but it looks insufficient to me as per the current Debian standards. Should you be interested in a submission to Debian, please answer my questions above, otherwise drop me a comment that you are not.

I have got a few questions:

- What is the versioning logic of your software? Are you using [semantic versioning](http://semver.org/) ? From the content of your list file, the SOVERSION is set to be the same as VERSION which conveys the message that you intend to break the ABI even for incremental patch versions. If you don't care about ABI compatibility, it is best left to **zero**. For now, I am assuming this is the case.

- Do you have a publication associated with the software ? If so, could you please paste a citation string and a bibtex reference for it, so I can include it to the package metadata.

I might have more questions as packaging progresses, so please don't close this issue until I am done.

Many thanks,

**Comment by Ulfgard** [comment]
Hi,

could you help me understand what part exactly do not conform to the current Debian standards? we would be happy to add some code into the CMakeLists.txt to make this happen

* Is "we do not care about ABI compatibility" the same as "we might break it at any time?" then currently, yes.
* The paper is currently under review

Best

**Comment by ghisvail** [comment]
> could you help me understand what part exactly do not conform to the current Debian standards?

Non exhaustive list, based on a quick look:

- The lintian issues currently overridden, should be addressed instead,

- Missing handling of multi-arch paths,

- The lack of modularity (should produce at least have a -dev and a versioned lib binary package, optionally a -dbg package and a -doc package),

- Additional Debian CI testing scripts, which are Debian specific.

> Is "we do not care about ABI compatibility" the same as "we might break it at any time?" then currently, yes.

In that case, please consider using `SOVERSION 0` in your library target. That way the corresponding lib package will be named libshark0, which conveys exactly this meaning (ABI might break anytime).

> The paper is currently under review

Congratulations. Wish you have a positive feedback. Please let us know when you have a reference for it so we can add the necessary upstream metadata.

**Comment by ghisvail** [comment]
> we would be happy to add some code into the CMakeLists.txt to make this happen

Great. I will forward you a few PRs as packaging progresses.

**Comment by ghisvail** [comment]
I now have a candidate package for Shark, but #25 is a blocker according to the Debian guidelines. Issue #22 would also need to be addressed to enable HDF5 support on Debian.

**Comment by Ulfgard** [comment]
Hi, I tried to fix #25 and the SOVERSION problem. I am currently trying to reproduce the HDF5 problem but I think I am going to fix it tomorrow. Thanks for all the work you put into it it is very much appreciated.

I think we will publish a shark 3.0.1 or 3.1.0 afterwards so that it is easy for you to pick up the changes

**Comment by Ulfgard** [comment]
What is wrong with #21? "If you don't care about ABI compatibility, it is best left to zero" was my impression to be what the change should be and https://cmake.org/cmake/help/v3.0/prop_tgt/SOVERSION.html says that I should do it this way.

Anyway, I fixed the hdf5 issue.

**Comment by ghisvail** [comment]
Your [commit](https://github.com/Shark-ML/Shark/blob/a1a68fdaf410527a1bb6a0f5c6acbfb6f0bb55ef/src/CMakeLists.txt) added a duplicate `set_target_properties`, which does not sound like the right thing to do here. I am not even sure whether that would work, since it might be overridden by the second `set_target_properties` below. Instead, my proposed [commit](https://github.com/ghisvail/Shark/blob/3252eae5e717dae1b9119b7d22a5a9a4189fbc5b/src/CMakeLists.txt) uses the existing `set_target_properties`.

**Comment by ghisvail** [comment]
> I think we will publish a shark 3.0.1 or 3.1.0 afterwards so that it is easy for you to pick up the changes.

Indeed, all I will have to do is merge the new tag in the packaging repository and drop the patches that have already been applied.

**Comment by ghisvail** [comment]
Would you guys consider pushing a new tag soon, so I can submit the package ?

**Comment by Ulfgard** [comment]
https://github.com/Shark-ML/Shark/releases/tag/3.0.1

done

**Comment by ghisvail** [comment]
It would be nice to keep the format of the tags consistent throughout the releases (`v3.0.0` now `3.0.1`). Please consider pushing a `v3.0.1` tag and remove the other one. Cheers.

**Comment by ghisvail** [comment]
Also the `SHARK_VERSION_PATH` was not incremented.

**Comment by ghisvail** [comment]
I have submitted a source package for inclusion to Debian for version `3.0.1`. Currently awaiting for a reviewer to process it.

**Comment by ghisvail** [comment]
Shark has just been accepted in [Debian](https://tracker.debian.org/pkg/shark). Closing.

**Comment by Ulfgard** [comment]
Sorry for my late reply I was on vacation, and got a bit tangled in other things.

Thanks for your work and efforts! This is a huge step forward. Is there any way we can further contribute to it? would we ping you every time we had a new release? or is this now handled "automagically"? 

Thanks again from the whole team!

**Comment by ghisvail** [comment]
@Ulfgard We have a watcher setup on the tags of the repository, so I should be alerted on any subsequent releases you guys make. FYI, Shark has now transitioned to Ubuntu, so it should be made available to the next release.
