### ISSUE TITLE
Error acessing shark-ml.org

### ISSUE THREAD

**Issue by mikini** [Shark-ML/Shark#219]
The [shark-ml.org](http://shark-ml.org) website domain mentioned in the project title redirects to an apparent defunct [image.diku.dk](http://image.diku.dk) server which is supposedly the home of the [DIKU Image section](http://diku.dk/english/research/imagesection/).

The same is true for the link to [Christian Igel's page](http://image.diku.dk/igel) on same server registered as the homepage of the [Shark-ML github organization](https://github.com/Shark-ML). [Christian's official staff page on diku](http://diku.dk/english/research/imagesection/members/?pure=en/persons/400547) is linking to the same server for his homepage (and also some other [prominent pages](http://diku.dk/english/research/imagesection/publica-tions/
)), so somehow something seems to be out of sync.

Trying to access image.diku.dk shows what is probably a firewall blocking requests on port 80 & 443:

```
$ dig ANY image.diku.dk +noall +answer

; <<>> DiG 9.10.3-P4-Ubuntu <<>> ANY image.diku.dk +noall +answer
;; global options: +cmd
image.diku.dk.		271	IN	A	130.226.12.119

$ nmap -Pn 130.226.12.119

Starting Nmap 7.01 ( https://nmap.org ) at 2018-02-05 16:53 CET
Nmap scan report for image.diku.dk (130.226.12.119)
Host is up (0.014s latency).
Not shown: 998 filtered ports
PORT    STATE  SERVICE
80/tcp  closed http
443/tcp closed https

Nmap done: 1 IP address (1 host up) scanned in 7.90 seconds

```
I have also reported this in an email to contact email info@di.ku.dk found at http://diku.dk/english/contact/.

**Comment by Ulfgard** [comment]
This is known. We have to set up a new server because of security problems with the old system.

**Comment by Ulfgard** [comment]
fixed
