### ISSUE TITLE
Random Forest serialization bug

### ISSUE THREAD

**Issue by inglada** [Shark-ML/Shark#220]
Hi,

The following code throws an exception when loading a saved RF model:

> terminate called after throwing an instance of 'boost::archive::archive_exception'
>   what():  input stream error
> Aborted
> 

The code is 
`#include <shark/Data/DataDistribution.h>
#include <shark/Algorithms/Trainers/RFTrainer.h>
#include <shark/ObjectiveFunctions/Loss/ZeroOneLoss.h>

using namespace shark;

int main ()
{
  PamiToy generator(5,5,0,0.4);
  auto train = generator.generateDataset(200);
  auto test = generator.generateDataset(200);

  RFTrainer<unsigned int> trainer(true,true);
  RFClassifier<unsigned int> model;
  RFClassifier<unsigned int> model2;
  trainer.train(model2,train);
  std::string filename = "rf.txt";
    
  std::ofstream ofs(filename.c_str());
  TextOutArchive oa(ofs);
  model2.save(oa,0);
  
  std::ifstream ifs(filename.c_str());
  TextInArchive ia(ifs);
  model.load(ia,0);
  //ia >> model;
  
  ZeroOneLoss<> loss;
  ZeroOneLoss<unsigned int, RealVector> loss2;
  double error_train = loss.eval(train.labels(), model(train.inputs()));
  double error_train2 = loss2.eval(train.labels(), model.decisionFunction()(train.inputs()));
  double error_test = loss.eval(test.labels(), model(test.inputs()));

  std::cout << "error : " << error_train <<std::endl;

}`

Thanks for your help.

**Comment by Ulfgard** [comment]
Hi

The archive is not written at the point where you want to read it. You have to close ofs or enclose the block with {}

This is so far not a bug
________________________________________

**Comment by inglada** [comment]
Sorry for the wrong report. We are having problems reading serialized models when we compile in release mode which disappear in debug mode. We use Shark with other libraries and we thought we had found the issue and wanted to provide a minimal example, which as you point out was incorrect.
We are still investigating the issue, but I will close this one and come back to you if Shark is the source of the bug.
Sorry again for bothering you.

**Comment by Ulfgard** [comment]
Hi,

we have the rF test failing on one older version of gcc, so maybe there is a bug. i will check again
________________________________

**Comment by Ulfgard** [comment]
i think i found the issue. It was indeed not directly in our code, it appears that some very large values of attributeIndex could crash the std::ostream. I fixed that by setting attributeIndex for leaves to 0.
