### ISSUE TITLE
Wrong behavior in RVEA::suggestMu function.

### ISSUE THREAD

**Issue by hriseb** [Shark-ML/Shark#223]
Hi,
the function 
std::size_t RVEA::suggestMu(std::size_t n, std::size_t const approx_mu)
of Algorithms/DirectSearch/RVEA.cpp does not do what is expected from it.

For a given number of objectives (n) and a desired value for mu (approx_mu) it should give 
the next closest possible value of mu. Instead it gives some value for mu. 
Example behavior: 
- RVEA::suggestMu( 7, 5) gives 28 (ok)
- RVEA::suggestMu( 7, 6) gives 28 (ok)
- RVEA::suggestMu( 7, 7) gives 28 (ok)
- RVEA::suggestMu( 7, 8) gives 84 ?? 
- RVEA::suggestMu( 7, 28) gives 84 ?? 
- RVEA::suggestMu( 7, 84) gives 210 ??
 
In particular, using the suggested mu for the next run actually produces another suggested mu and so on...

**Comment by Ulfgard** [comment]
This should be fixed now. You can just cherry pick the commit above.

**Comment by hriseb** [comment]
Thanks, now it basically works. One thing, in Lattice.h line 85, the namespace detail:: needs to be added ti the sumlength function call.: 
it should read 
while(detail::sumlength(n, dimension_ticks_count) < target_count){ ...

**Comment by Ulfgard** [comment]
thank you. i did a direct edit on github, thought it was a one-liner...well never skip testing :)
