### ISSUE TITLE
Assertion failed when computing feature importances for RF

### ISSUE THREAD

**Issue by inglada** [Shark-ML/Shark#227]
When activating the computation of feature importances in RF with 
  shark::RFTrainer<unsigned int> trainer(true, false);

the training step fails with this error:

include/shark/LinAlg/BLAS/detail/../kernels/default/../../cpu/dense.hpp:836: remora::vector<T, remora::cpu_tag>::reference remora::vector<T, remora::cpu_tag>::operator[](remora::vector<T, remora::cpu_tag>::size_type) [with T = double; remora::vector<T, remora::cpu_tag>::reference = double&; remora::vector<T, remora::cpu_tag>::size_type = long unsigned int]: Assertion `i < size()' failed.

Here goes the complete backtrace as given by gdb:

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fffe6e0a42a in __GI_abort () at abort.c:89
#2  0x00007fffe6e01e67 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x55555571683d "i < size()", file=file@entry=0x5555557167d8 "/home/inglada/OTB/SuperBuild/include/shark/LinAlg/BLAS/detail/../kernels/default/../../cpu/dense.hpp", line=line@entry=836, function=function@entry=0x55555571c2e0 <remora::vector<double, remora::cpu_tag>::operator[](unsigned long)::__PRETTY_FUNCTION__> "remora::vector<T, remora::cpu_tag>::reference remora::vector<T, remora::cpu_tag>::operator[](remora::vector<T, remora::cpu_tag>::size_type) [with T = double; remora::vector<T, remora::cpu_tag>::refere"...) at assert.c:92
#3  0x00007fffe6e01f12 in __GI___assert_fail (assertion=0x55555571683d "i < size()", file=0x5555557167d8 "/home/inglada/OTB/SuperBuild/include/shark/LinAlg/BLAS/detail/../kernels/default/../../cpu/dense.hpp", line=836, function=0x55555571c2e0 <remora::vector<double, remora::cpu_tag>::operator[](unsigned long)::__PRETTY_FUNCTION__> "remora::vector<T, remora::cpu_tag>::reference remora::vector<T, remora::cpu_tag>::operator[](remora::vector<T, remora::cpu_tag>::size_type) [with T = double; remora::vector<T, remora::cpu_tag>::refere"...) at assert.c:101
#4  0x00005555556b2573 in remora::vector<double, remora::cpu_tag>::operator[](unsigned long) ()
#5  0x00005555556c15c3 in shark::detail::EnsembleImpl<shark::CARTree<unsigned int>, remora::vector<double, remora::cpu_tag> >::weight(unsigned long) ()
#6  0x00005555556ba898 in shark::Ensemble<shark::CARTree<unsigned int>, void>::weight(unsigned long) ()
#7  0x00005555556b4743 in shark::RFClassifier<unsigned int>::computeFeatureImportances(std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > const&, shark::LabeledData<remora::vector<double, remora::cpu_tag>, unsigned int> const&, std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>&) ()
#8  0x00005555556b0c9e in shark::RFTrainer<unsigned int>::train(shark::RFClassifier<unsigned int>&, shark::WeightedLabeledData<remora::vector<double, remora::cpu_tag>, unsigned int> const&) ()
#9  0x00005555556b5ce2 in shark::AbstractWeightedTrainer<shark::RFClassifier<unsigned int>, unsigned int>::train(shark::RFClassifier<unsigned int>&, shark::LabeledData<remora::vector<double, remora::cpu_tag>, unsigned int> const&) ()
#10 0x00005555556ac6b8 in main ()

Thank you.

**Comment by inglada** [comment]
Hi,
Is there anything I could do to help you investigate this issue?
Thanks.

**Comment by Ulfgard** [comment]
reminding me was enough :)

**Comment by Ulfgard** [comment]
i think this one is fixed, right?

**Comment by inglada** [comment]
On Mon 11-Jun-2018 at 07:10:44 +0200, Oswin Krause <notifications@github.com> wrote: 
> i think this one is fixed, right?
>

Yes. Thanks.
