### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by sungliner** [Shark-ML/Shark#229]
[ 10%] Linking CXX executable ../bin/OneClassSvm
[ 10%] Built target OneClassSvm
[ 10%] Linking CXX executable ../bin/DenoisingAutoencoderTutorial
[ 10%] Built target DenoisingAutoencoderTutorial
[ 10%] Linking CXX executable ../bin/SparseAETutorial
[ 10%] Built target SparseAETutorial
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by inglada** [comment]
Hi,
Can you provide more information? Are you trying to install into /usr/local/bin without being root, for instance?

**Comment by Ulfgard** [comment]
Hi,

I need a complete error log. Right now you are not showing the error.

This does not look like it is the current development version. We will release a new version of shark soon.

**Comment by Ulfgard** [comment]
please, reopen if you are still installing
