### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by sungliner** [Shark-ML/Shark#233]
hi!
  i want to use LinearRegression,you know it need input data just like this: RegressionDataset data(inputs, labels);
  but now i dont want initialize Data<RealVector> inputs and Data<RealVector> labels from a CSV file by importCSV() function 
  is there some way i can initialize Data<RealVector>and Data<RealVector>by myself

**Comment by Ulfgard** [comment]
you can initialize it with two std::vector<RealVector> and createLabeledDataFromRange

http://www.shark-ml.org/doxygen_pages/html/group__shark__globals.html#ga0e4ef7276207a92fdb2b3dd8dddd16f7

i close this, as this is no issue, but feel free to comment if this is not solving your problem
