### ISSUE TITLE
model

### ISSUE THREAD

**Issue by sungliner** [Shark-ML/Shark#234]
hi!
     if we have alreadly trained  a model ,can we store the trained model and use it nextime?

**Comment by Ulfgard** [comment]
yes, you can use boost::serialization for it. See this tutorial

http://www.shark-ml.org/sphinx_pages/build/html/rest_sources/tutorials/concepts/misc/serialization.html

and our tutorial section:
http://www.shark-ml.org/sphinx_pages/build/html/rest_sources/tutorials/tutorials.html
