### ISSUE TITLE
Data_Download acting up again

### ISSUE THREAD

**Issue by Ulfgard** [Shark-ML/Shark#239]
Since a few days, afte ra longer mldata downtime (i think it still down):

101/145 Test #101: Data_Download ...........................................***Failed  152.63 sec
Running 3 test cases...
/home/travis/build/Shark-ML/Shark/Test/Data/Download.cpp(40): error in "Data_Download_URL": Got exception [download] http protocol violation
/home/travis/build/Shark-ML/Shark/Test/Data/Download.cpp(63): error in "Data_Download_MLData": Got exception [download] http protocol violation
*** 2 failures detected in test suite "ML_Download"

how good is a binding to a webpage that is always down?

**Comment by TGlas** [comment]
mldata.org does not seem to be well-maintained already for years. The simplest solution is to link to our self-hosted data used in the "hello world" tutorial at [](http://www.shark-ml.org/data/quickstart-train.csv).

**Comment by Ulfgard** [comment]
should we remove the mldata download facility? just use the url download?
________________________________

**Comment by TGlas** [comment]
Let remove mldata.

**Comment by TGlas** [comment]
A different issue is that we only support http, not https. This will be an increasing issue in the future. That would cost us an openssl dependency, which could be optional. Would you consider that worth the hassle?

**Comment by Ulfgard** [comment]
i hav a tendency towards "no". I think this function is only relevant for the first steps to get started smoothly. but nothing relevant.
________________________________

**Comment by TGlas** [comment]
If we remove mldata.org support, then we could also remove support for the HDF5 data set format. As far as I know, mldata is the only platform that pushed the format, and as far as I can tell it was not widely adopted.

**Comment by TGlas** [comment]
mldata support removed, docs, tests and examples updated accordingly

**Comment by Ulfgard** [comment]
Fully agreed. Kill it. Also remove scoped handle from core
________________________________________

**Comment by TGlas** [comment]
Just to be sure: "Fully agreed. Kill it." refers to HDF5 support, not to my short post above?

**Comment by Ulfgard** [comment]
yes. kill hdf5 support
________________________________

**Comment by TGlas** [comment]
done.
