### ISSUE TITLE
Remove override of CMAKE_BUILD_TYPE

### ISSUE THREAD

**Issue by ghisvail** [Shark-ML/Shark#24]
Taken from the root `CMakeLists.txt`, the following snippet:

```
string( TOLOWER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE )
if(${CMAKE_BUILD_TYPE}  MATCHES "debug")
	#we want to be warned in debug mode
	if(UNIX)
#		if(CMAKE_COMPILER_IS_GNUCC)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
#		endif()
	endif()
endif()
```

is bad, as it overrides the value of `CMAKE_BUILD_TYPE` and prevents CMake doing its magic when using the `RelWithDebInfo` configuration (useful for Debian packaging). Please consider an alternative solution, such as using a different variable to store the converted string.

**Comment by Ulfgard** [comment]
i replaced this simply by

    if (UNIX)
        add_compile_options("$<$<CONFIG:DEBUG>:-Wall>")
    endif()

**Comment by ghisvail** [comment]
Your proposed fix is not making the tarvis-ci builders happy.

**Comment by Ulfgard** [comment]
hmm. this functionality apparently got introduced with cmake 2.8.12 and travis-ci ha an older cmake.

**Comment by Ulfgard** [comment]
i have updated the builder with version 2.8.12 and this build passes.

**Comment by ghisvail** [comment]
Brilliant. Thanks for addressing this.
