### ISSUE TITLE
Shark is not working

### ISSUE THREAD

**Issue by John1911603424** [Shark-ML/Shark#248]
I have successfully compiled shark, but cannot run "RFTrainer.cpp". There exist many errors, such as importCSV, LAST_COLUMN, ... and RFTrainer, RFClassifier,... ,which cannot be identified.

**Comment by Ulfgard** [comment]
There is not enough information to help and without the exact error messages i have zero chance to guess it. So lets start with the basics:
As "RFTrainer.cpp" is not a program, what does "cannot run" mean? As you have successfully compiled shark, I am quite sure that all examples got build. I guess you wanted to use shark in your own project and uses RFTrainer.cpp as a starting code?

Which brings me to the main question:
Have you followed the tutorials for compiling your own projects?
http://www.shark-ml.org/sphinx_pages/build/html/rest_sources/tutorials/first_steps/your_programs.html

**Comment by John1911603424** [comment]
I have solved this problem. It should set boost "include path" of VS project property to the Boost root path
