### ISSUE TITLE
Why the RFTrainer is very slow?

### ISSUE THREAD

**Issue by John1911603424** [Shark-ML/Shark#252]
It was very slow that using the RFTrainer to train 600000 samples with 4 features in shark  3.0.0, and it didn't finish after waiting for dozens of minutes. When I use Random Forest to train the same data in sklearn, it took only a few seconds. So what is the reason? Did I lose other libraries when I compiled it?

**Comment by John1911603424** [comment]
Thank you. I will try it.

**Comment by cydcydcyd** [comment]
> Thank you. I will try it.

Hi，is Version 4.0 faster?
