### ISSUE TITLE
[Shark installation]Issue while running make command

### ISSUE THREAD

**Issue by souchtal** [Shark-ML/Shark#256]
I am installing Shark 3.0.0 on ubuntu-bionic-18.04-amd64, the last step of the installation fails because of error(1):
![image](https://user-images.githubusercontent.com/32470115/46965398-5a052000-d070-11e8-9a43-485b6c720055.png)
I tried to fixed the issue by adding the possibly missing parenthesis to the header file (../include/shark/Rng/Dirichlet.h), the execution of the make command does not fail this time, but it gets stuck at 
![image](https://user-images.githubusercontent.com/32470115/46965857-92592e00-d071-11e8-9929-5410bb1511af.png)

Any ideas why the original error might have been generated? is it a possible syntax error? or a system dependency?
(I am using Shark for one of my graduate projects)

Thanks.

**Comment by Ulfgard** [comment]
we are at release 4.0 now (and in between there were a few 3.1 versions). Please try some of our later releases
