### ISSUE TITLE
Inconsistent encoding in CMSA{.h,.cpp} files

### ISSUE THREAD

**Issue by ghisvail** [Shark-ML/Shark#26]
The `CMSA` files have a different encoding (unknown) than the rest of the project (`ascii`):
```
file -bi include/shark/Algorithms/DirectSearch/CMSA.h
text/x-c; charset=unknown-8bit
```

Please consider converting the files to a known format such as `unicode` if `ascii` is not an option. The current format prevents standard unix text parsers to operate on these files.

**Comment by Ulfgard** [comment]
thank you. There were a few weird signs in a comment from a paper title. This is now fixed
