### ISSUE TITLE
x64

### ISSUE THREAD

**Issue by dry11orange** [Shark-ML/Shark#266]
Is there a way to build shark x64 with vs2015

**Comment by Ulfgard** [comment]
you should be able to select an x64 build in either cmake or the ide

**Comment by dry11orange** [comment]
I tried, But I found no x64 in cmake or ide
![2019-03-05_104719](https://user-images.githubusercontent.com/24197508/53777393-2dc14180-3f34-11e9-840e-94c644984827.png)
![2019-03-05_104733](https://user-images.githubusercontent.com/24197508/53777396-30239b80-3f34-11e9-8014-cc18195b73f2.png)

**Comment by Ulfgard** [comment]
On older versions of visual studio, the first time you set up the build folder with cmake and click on "generate" cmake will ask you what platform to build for. there are two versions, one having "-win64" appended to the end. I do not run windows and do not use visual studio aside from automatic build testing (and an occasional run via visual studio code). So i am not sure about all the details on your platform.

**Comment by dry11orange** [comment]
ok, Thank you!!
