### ISSUE TITLE
can't install shark

### ISSUE THREAD

**Issue by yinggudk** [Shark-ML/Shark#276]
First I downloaded boost, then run bootstrap.bat, then run b2. Then I can call functions from boost in VC2019 community.
Later on, I installed boost through vcpkg.
Now I tried to install shark-ml and failed. The following is from cmake-gui:
*********************************************************************************************************
Will build: release
CMake Error at D:/libraries/Cmaker/cmake-3.17.2-win64-x64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR system date_time
  filesystem program_options serialization thread unit_test_framework)
  (Required is at least version "1.48.0")
Call Stack (most recent call first):
  D:/libraries/Cmaker/cmake-3.17.2-win64-x64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  D:/libraries/Cmaker/cmake-3.17.2-win64-x64/share/cmake-3.17/Modules/FindBoost.cmake:2162 (find_package_handle_standard_args)
  CMakeLists.txt:146 (find_package)

Configuring incomplete, errors occurred!
See also "D:/libraries/Shark-3.0.0/build_shark/CMakeFiles/CMakeOutput.log".
See also "D:/libraries/Shark-3.0.0/build_shark/CMakeFiles/CMakeError.log".
*********************************************************************************************************
 I followed installation guide on Windows and Visual Studio. Can't make it work.
What could be wrong?¶

**Comment by Ulfgard** [comment]
you need to tell cmake where boost is located. I think this is -DBOOST_ROOT=/PATH/TO/BOOST

i don't know where vcpkg installs boost to.

________________________________________
