### ISSUE TITLE
Is Shark dead?

### ISSUE THREAD

**Issue by javiermaldonadoc** [Shark-ML/Shark#277]
Hello,
I've working with Shark for almost a 2 years... but i don't see any updates and new documentation. This is a wonderful library... Is Shark dead now? :-(

**Comment by Ulfgard** [comment]
Hi,

no we hope not. right now we have other priorities (we unfortunately don't have any funding for development and I am done with my PhD so I have a lot of other things on my desk now).
There is active work going on in remora, though and we hope that this will allow us to include full gpu support in the future.
________________________________________

**Comment by richelbilderbeek** [comment]
Hmmm, two years later and still no updates ...

Which actively maintained C++ library is recommended to use nowadays?

**Comment by Ulfgard** [comment]
Hi,

I am sorry for the lack of progress. I got burnout 18 months ago and I am currently not in the capacity to maintain this library actively. I would still want to work on it, but there is only so much energy i have left.

**Comment by conradsnicta** [comment]
> Hmmm, two years later and still no updates ...
> 
> Which actively maintained C++ library is recommended to use nowadays?

@richelbilderbeek try ensmallen and mlpack:
* https://github.com/mlpack/ensmallen/
* https://github.com/mlpack/mlpack/

**Comment by christian-igel** [comment]
Hi,
No, it is not fully abandoned. 
There is no active development, but we try to maintain the library.
The new homepage will be here:
https://shark-ml.github.io/Shark/
Best wishes,
Christian
