### ISSUE TITLE
error during make

### ISSUE THREAD

**Issue by ManiAm** [Shark-ML/Shark#30]
Hi,

I cloned the shark repository on my Ubuntu 14, 64-bit machine and followed the installation instructions. I got an error at the beginning of the make process:

![mani mani-thinkpad-t430s -desktop-shark-build_009](https://cloud.githubusercontent.com/assets/5473998/11606867/57d476aa-9ae5-11e5-8df0-7f7e09ef0079.png)

But I can see the clapack.h header file in /usr/include/atlas/clapack.h.

P.S. I have installed all the required packages before installing Shark.

**Comment by Ulfgard** [comment]
your distribution puts clapack.h in a different include directory then we were expecting (/usr/include). Thanks for the report, I will try to fix it later today

**Comment by ManiAm** [comment]
Thanks! For now I modified the cmake cache file to point to the atlas directory.

Now I can build shark successfully. Linking the libshark library to my C++ program gives me the following error: /usr/local/lib/libshark.so.0: undefined symbol: clapack_dpotrf

P.S. I have installed libatlas-base-dev.

**Comment by Ulfgard** [comment]
do you use cmake to link shark to it? or do you use your own makefile? in this case you have to remember to also link to the lapack library which comes with atlas

**Comment by ManiAm** [comment]
I am using my own makefile and I am linking to both shark and lapack. So is this something related to lapack library?

In the installation page, under dependencies, you only mentioned to install these packages for Ubuntu:

sudo apt-get install cmake cmake-curses-gui libatlas-base-dev libboost-all-dev

I have libatlas-base-dev version 3.10

**Comment by Ulfgard** [comment]
this is all part of the atlas package. can i see your link command?

**Comment by ManiAm** [comment]
This is my makefile:

https://www.dropbox.com/s/p0kw5ijk3294wra/Makefile?dl=0

This makefile is part of a hierarchical makefile structure and might look a little bit complicated. Please search for lshark. You can find it under # Additional libraries (-L, -l options)

By the way, googling this error brings these discussions (which are old).

https://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=2&t=2096
http://www.astromatic.net/forum/showthread.php?tid=880
http://lists.freebsd.org/pipermail/freebsd-ports/2007-July/042793.html
http://comments.gmane.org/gmane.comp.ai.machine-learning.shogun/875

From the last link, it seems that this is a bug in the ubuntu atlas/lapack libraries.

**Comment by Ulfgard** [comment]
I do not think that this is a problem of your atas package or shark, because you could compile shark! (to make this sure you can try compiling the examples, as the examples make use of this symbol.

indeed, your makefile is not very helpful :/. 
could you try issuing make -n on the failing target so that we can see the actual compiler options? 

Be aware that link-order of libraries is important. linking to lapack before linking to shark will also cause this error as the linker will only search for symbols after they were introduced as required, thus first linking to lapack will resolve nothing and then resolving shark will introduce the symbols.

**Comment by ManiAm** [comment]
I solve the issue by linking to 'lapack_atlas' library rather than 'lapack'.
