### ISSUE TITLE
shark::Individual should implement shark::ISerializable

### ISSUE THREAD

**Issue by bjornbugge** [Shark-ML/Shark#32]
The Individual class in Algorithms/DirectSearch/Individual.h does not inherit from shark::ISerializable.  This appears to be a mistake, as shark::Individual does implement a serialization call.

**Comment by Ulfgard** [comment]
This is not a problem, as boost serialization does not require the use of a base class. The only thing this allows is the (de)serialization of abstract base-classes when the classes themself are not registered to the serializer (i.e. the user keeps track of the types). This is required in cases where we use type-erasures (e.g. ConcenatedModel). The individual classes are not one of these cases.

**Comment by bjornbugge** [comment]
But wouldn't it be prettier if it declared that it was serializable, seeing as it is so?  It would make it simpler for users to write something takes takes "anything that Shark knows how to serialize", e.g.

**Comment by Ulfgard** [comment]
This approach has the disadvantage as the ISerializable interface only works with polymorphic archives, while the "normal" boost serializable interface always works. Are you stumbling over this problem right now?

**Comment by bjornbugge** [comment]
Okay, fair enough.  I did run into it, but it's not overly difficult to handle.  I just thought it would make sense for a class to "broadcast" that it can be serialized.
