### ISSUE TITLE
SegFault in Ubuntu 15.10 Desktop

### ISSUE THREAD

**Issue by ManiAm** [Shark-ML/Shark#36]
I have problem using Shark in Ubuntu 15.10. In Ubuntu 14 everything seems to be working ok but the same C++ program in Ubuntu 15.10 gives me segmentation fault and my program crashes.

Program received signal SIGSEGV, segmentation fault in
_GLOBAL__sub_I_KernelBasisDistance.cpp () from /usr/local/lib/libshark.so.0

![screenshot from 2016-01-24 12 01 15](https://cloud.githubusercontent.com/assets/5473998/12538656/c1a70aa4-c293-11e5-89a8-ce0dd2673bab.png)

**Comment by Ulfgard** [comment]
This seems like you are using Shark in your module, but without providing any information the error you encounter is unlikely to be fixable as we can not know how you are using it.  Which shark component are you using and at which point in your code is it crashing?

did you try the following:

1. compile in debug mode and link to shark_debug.so (requires compiling shark in debug as well)
2. let your debugger run

**Comment by ManiAm** [comment]
I had changed the CBLAS_INCLUDES path to this cause shark was not able to detect it in Ubuntu:

cmake "DCBLAS_INCLUDES:FILEPATH=/usr/include/atlas/cblas.h" ../

I removed the above option, and everything seems to be working!
