### ISSUE TITLE
linking error in Mac OS el capitan

### ISSUE THREAD

**Issue by ManiAm** [Shark-ML/Shark#37]
I have installed the shark library on Ubuntu and linked it with libshark_debug.so and liblapack_atlas.so. liblapack_atlas.so was in libatlas-base-dev package.

Now I want to do the same on Mac OS X, but I can not find liblapack_atlas.so. Linker stops with this error:

undefined symbols for architecture x86_64:
"_cblas_dgemm", reference from:
shark::blas::binding::gemm()

Which package should I install (using brew for instance) to be able to link my C++ program with liblapack_atlas.so.

**Comment by Ulfgard** [comment]
Atlas?

but on MacOsX you should instead use Accelerate, which is used by shark as default on that platform.

________________________________

**Comment by ManiAm** [comment]
Ok. So what library should I link my C++ program to (besides shark_debug) in order to solve the linkage error?

**Comment by Ulfgard** [comment]
you have to enable the accelerate framework when compiling shark on OsX using ENABLE_CBLAS=ON and when you link your program jut do:

clang -framework Accelerate

or you just use the provide CMakeLists.txt which should set everything up automatically


________________________________

**Comment by Ulfgard** [comment]
is this resolved? closing it because so old. Feeel free to reopen if there is still an issue :)
