### ISSUE TITLE
Rewrite pgm.h to use iostreams and no printf

### ISSUE THREAD

**Issue by Ulfgard** [Shark-ML/Shark#4]
Currently, we have to workaround and use a lot of cast which is not needed. So rewrite and make it easier.

the implementation should also be moved into the library as it is template independent.

**Comment by skn123** [comment]
Why not add a tpl for image I/O? Like ITK or gdal?

**Comment by Ulfgard** [comment]
Sorry, what do you mean?

**Comment by skn123** [comment]
Why not use GDal for all Image IO work?
