### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by ManiAm** [Shark-ML/Shark#40]
At the top of the shark/Data/Dataset.h file, there is an example of accessing elements of type Data:

///typedef Data<RealVector> Set;
/// Set data;
/// for(Set::element_iterator pos=data.elemBegin();pos!= data.elemEnd();++pos){
///     std::cout<<*pos<<" ";
///     Set::element_reference ref=*pos;
///     ref*=2;
///     std::cout<<*pos<<std::endl;
///}

I can not make this example work! C++ shows this error message:

‘element_iterator’ is not a member of ‘Set {aka shark::Data<shark::blas::vector<double> >}’

**Comment by Ulfgard** [comment]
you are right. This code is outdated. Sorry! Thanks for reporting this. 

in C++11 you can simply do

for(auto element: data.elements())
   std::cout<<element<<" ";

**Comment by Ulfgard** [comment]
fixed
