### ISSUE TITLE
Lapack issue: undefined symbol: clapack_dpotrf

### ISSUE THREAD

**Issue by Fractally** [Shark-ML/Shark#41]
Hey guys

I tried to compile Shark on my Ubuntu (14.04) machine and ran into an error while compiling one of the examples. Lapack on my machine does not include dpotrf (undefined symbol: clapack_dpotrf). 

I assume that it is necessary to build Atlas myself instead of using the available package on Ubuntu if I need dpotrf (and maybe other functions)? Can someone please confirm this?

Also has anyone used Intel's MKL with Shark?

Thanks!

**Comment by Ulfgard** [comment]
This looks like a lapack implementation without lapacke (the c bindings). that is a bit odd. do you know which ubuntu package this is? Maybe we should extend our search routines to also search for that..hmm..

We have no experience with MKL whatsoever.

**Comment by Fractally** [comment]
My Atlas's clapack header does provide the function declaration for dpotrf. I am using ATLAS 3.10 which came with Ubuntu 14.04 as far as I'm aware of. More info about the Ubuntu ATLAS packages [here](http://packages.ubuntu.com/search?suite=trusty&section=all&arch=any&keywords=atlas&searchon=names).

Without yet knowing the inside of Shark, I won't be trying to substitute ATLAS with MKL just yet. I'll continue to search for a solution today. Any ideas would be great.

Thanks!

**Comment by Fractally** [comment]
I built ATLAS myself, but it does not solve the problem. Looking into this further.

**Comment by Ulfgard** [comment]
Interesting. Maybe the system somehow pics up a wrong lapack library? could you try to verify (e.g. make -n) which lapack libraries are linked?

**Comment by Fractally** [comment]
From Cmake:

> ATLAS_LIBRARY = /usr/lib/libatlas.so
> CBLAS_INCLUDES = /usr/include/cblas.h
> CBLAS_LIBRARY = /usr/lib/libcblas.so
> CLAPACK_INCLUDES = /usr/include/atlas/clapack.h
> CLAPACK_LIBRARY = /usr/lib/liblapack.so

The files above all exist. May I ask where your includes and libraries are? I've noticed that there are liblapack.so.3 and libatlas.so.3 libraries on my machine also. I will try them and see if the results differ.

**Comment by Fractally** [comment]
The ".so.3" libraries also have the following error when linking CXX executable ../bin/CSvmMaxLikelihoodMS:

> undefined reference to `clapack_dpotrf'

**Comment by ManiAm** [comment]
Yes I had the same issue. You need to install package "libatlas-base-dev"

sudo pat-get install libatlas-base-dev

and then link your program with -llapack_atlas

**Comment by Fractally** [comment]
Hi ManiAm,

Thanks for your input. I've had that lib installed already and also have been linking to the correct libraries as far as I can tell (I tried the normal ubuntu ATLAS and built my own version). The solution to my problem still evades me. I decided to build OpenBlas and use it instead. I have compiled everything just fine now so I can finally start playing with Shark. I wonder if this means that cblas was the issue. The only thing I changed was to include the path to libopenblas.so. 

Thanks for all the help. If at all possible, could someone share their library paths and include paths for ATLAS, cblas and lapack? Would just like to compare in case I missed something. I'll stick with OpenBlas in the mean time.

**Comment by Ulfgard** [comment]
My guess would be that aside of ATLAS there is another lapack library installed (/usr/lib/lapack.so) and it does not pick up the atlas lapack (which could be /usr/lib/Atlas/lapack.so) as the /usr/lib/lapack might not have lacpake this would explain the issue. This is REALLY fiddly on ubuntu.

**Comment by Fractally** [comment]
Hi Ulfgard

I think you might be right! There is another installed. I'll see if I can remove it and report back. With any luck I can close this issue then. Also I am curious as to whether OpenBlas would be faster than the normal blas package. 

Thanks for all the help!

**Comment by Ulfgard** [comment]
is this resolved?
