### ISSUE TITLE
Initialization of SMS-EMOA

### ISSUE THREAD

**Issue by bjornbugge** [Shark-ML/Shark#42]
In the call to SMSEMOA::doInit, if startingPoints.size() is greater than mu, line 197 is reached with numPoints==0: 
https://github.com/Shark-ML/Shark/blob/InterfaceEvo/include/shark/Algorithms/DirectSearch/SMS-EMOA.h#L197
The call to Rng::discrete is then fed the interval (0,-1) and since -1 is a std::size_t it is interpreted as a very large number like (18446744073709551615).  The index picked is therefore with high probability out of bounds when used in the next line. @Ulfgard

**Comment by Ulfgard** [comment]
arrgh! head->wall it must be mu-numPoints-1

**Comment by bjornbugge** [comment]
:+1:  :-)
