### ISSUE TITLE
Feature importance in random forest

### ISSUE THREAD

**Issue by jaelim** [Shark-ML/Shark#45]
I'm working on a classification problem with a multi-class dataset. I'm trying to model a random forest and tried to extract feature importance. However, when I ran and extracted the importance variable, it contained nothing.

Could someone provide some directions on how to use feature importance option correctly with an example? Thanks a lot.

**Comment by Ulfgard** [comment]
Hi,

sorry for the late reply. You have to inform the RFTrainer class that you want the importances. This is set in the constructor, which by default skips OOB_Error and FeatureImportances.

RFTrainer(bool computeFeatureImportances = false, bool computeOOBerror = false);

so the following helps:

RFTrainer trainer(true);

**Comment by jaelim** [comment]
@Ulfgard Hi, Thanks for replying back. It worked! Strangely I had this in my code before which did not work:
`bool computeFeatureImportances=true, computeOOBerror=true;RFTrainer(computeFeatureImportances, computeOOBerror);`
It did run without throwing an exception or a crash. It ran and nothing output. But, with your suggestion, I now see my feature importance result.

There's another thing I want to inquire you. I got my OOB error which is strangely to be too small:
`OOB error:	   6.95299e-310`
I extracted the OOB error using following code:
`model.OOBerror()`
where 
`RFClassifier model;`
Is this suppose to generate this small number?

**Comment by Ulfgard** [comment]
did you have the code like that? in that case you would create a trainer object which is then immediately destroyed. so it can not do what you wnated to do.

for the OOB error to be set you have to also set the second argument to true

**Comment by jaelim** [comment]
@Ulfgard Thank you again! Everything worked out fine. I got an OOB error that makes a lot more sense.
Just reading the current documentation, nor an example to learn from, it would have been very difficult for me to figure out. Thanks for your help.
