### ISSUE TITLE
OpenBlas support

### ISSUE THREAD

**Issue by skn123** [Shark-ML/Shark#5]
I would like to submit a patch that would enable usage of OpenBlas. How do I go about doing this?

**Comment by Ulfgard** [comment]
Hi,

cool to see this! The easiest way is probably a pull request, then we can check it out, test and code-review this. I am really looking forward to this!

**Comment by Ulfgard** [comment]
Hey, what is the status about this? :)

**Comment by skn123** [comment]
I am stuck at a very silly stage: I do not / am not able to send a "push_request" :( I am using Tortoise Git on windows

**Comment by Ulfgard** [comment]
Hi, okay, i try to help you setting this up. This might take a few minutes and as i do not use TortoiseGit i had to use all my googleFu skills :). It will be very helpful a i can give you detailed comments and see your commits etc :)

1. on the top-right on https://github.com/Shark-ML/Shark/ , click on "fork" and fork the shark library into your account, this should lead to a fork at https://github.com/skn123/Shark
2. next we need to point your local repository to your new fork so that you can upload your data to github: http://stackoverflow.com/questions/14503381/change-repo-url-in-tortoisegit
3. For future usage you also want to keep our repository as your upstream reference to update your fork when needed. This link explains how that works:
http://stackoverflow.com/questions/7297486/can-i-update-a-forked-project-on-git-to-the-original-master-copy
4. after this you can just do a push to "origin" which is now your fork.
5. on https://github.com/skn123/Shark you should see a green button with two arrows. this will create your pull request.

If you have any questions, do not hesitate to contact me!

**Comment by skn123** [comment]
Wow; Now that has made my life easier. However, am I assured that any changes done in Shark-Master will also be reflected in my clone?

https://github.com/Shark-ML/Shark/pull/18

**Comment by Ulfgard** [comment]
Hej, sorry for the longer waiting time.

I took your code and tried to integrate it in our existing atlas/cblas code without duplication everything.

This can be found in pull-request #20.

Would you like to test whether this works in your local setup? i think you have to specify the CBLAS_PATH in cmake to find your installation of OpenBLAS.

regarding your question: you have to do a "git pull upstream" to get the changes in shark-master

**Comment by skn123** [comment]
I will do that shortly...

**Comment by skn123** [comment]
Severity	Code	Description	Project	File	Line
Error	C2668	'shark::size': ambiguous call to overloaded function	shark	F:\GItSources\Shark\src\Models\RNNet.cpp	46
Error	C2668	'shark::size': ambiguous call to overloaded function	shark	F:\GItSources\Shark\src\Models\RNNet.cpp	42
Error	C2668	'shark::size': ambiguous call to overloaded function	shark	F:\GItSources\Shark\src\Models\RNNet.cpp	43
Error	C2668	'shark::size': ambiguous call to overloaded function	shark	F:\GItSources\Shark\src\Models\RNNet.cpp	47
Error	C2668	'shark::size': ambiguous call to overloaded function	shark	F:\GItSources\Shark\src\Models\RNNet.cpp	49
Error	C2668	'shark::size': ambiguous call to overloaded function	shark	F:\GItSources\Shark\src\Models\RNNet.cpp	93
Error	C2668	'shark::size': ambiguous call to overloaded function	shark	F:\GItSources\Shark\src\Models\RNNet.cpp	95
Error	C3203	'type': unspecialized class template can't be used as a template argument for template parameter 'T0', expected a real type	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\container\vector\detail\cpp03\preprocessed\as_vector10.hpp	62
Error	C3203	'type': unspecialized class template can't be used as a template argument for template parameter 'T1', expected a real type	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\container\vector\detail\cpp03\preprocessed\as_vector10.hpp	62
Error	C3203	'type': unspecialized class template can't be used as a template argument for template parameter 'T2', expected a real type	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\container\vector\detail\cpp03\preprocessed\as_vector10.hpp	62
Error	C3203	'type': unspecialized class template can't be used as a template argument for template parameter 'T0', expected a real type	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\container\vector\detail\cpp03\preprocessed\as_vector10.hpp	62
Error	C3203	'type': unspecialized class template can't be used as a template argument for template parameter 'T1', expected a real type	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\container\vector\detail\cpp03\preprocessed\as_vector10.hpp	62
Error	C3203	'type': unspecialized class template can't be used as a template argument for template parameter 'T2', expected a real type	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\container\vector\detail\cpp03\preprocessed\as_vector10.hpp	62
Error	C2039	'type': is not a member of 'boost::mpl::apply<boost::fusion::detail::apply_transform_result<boost::spirit::traits::build_attribute_sequence<Elements,Context,boost::spirit::traits::sequence_attribute_transform,Iterator,boost::spirit::qi::domain>::element_attribute>,boost::spirit::qi::kleene<boost::spirit::qi::alternative<boost::fusion::cons<boost::spirit::qi::sequence<boost::fusion::cons<boost::spirit::qi::any_real_parser<T,Policies>,Cdr>>,boost::fusion::cons<boost::spirit::qi::sequence<boost::fusion::cons<boost::spirit::qi::literal_char<boost::spirit::char_encoding::standard,true,false>,boost::fusion::cons<boost::spirit::qi::attr_parser<const double>,boost::fusion::nil_>>>,boost::fusion::nil_>>>>,boost::mpl::na,boost::mpl::na,boost::mpl::na,boost::mpl::na>'	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\view\transform_view\detail\value_of_impl.hpp	37
Error	C2039	'type': is not a member of 'boost::mpl::apply<boost::fusion::detail::apply_transform_result<boost::spirit::traits::build_attribute_sequence<Elements,Context,boost::spirit::traits::sequence_attribute_transform,Iterator,boost::spirit::qi::domain>::element_attribute>,boost::spirit::qi::lexeme_directive<Subject>,boost::mpl::na,boost::mpl::na,boost::mpl::na,boost::mpl::na>'	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\view\transform_view\detail\value_of_impl.hpp	37
Error	C2039	'type': is not a member of 'boost::mpl::apply<boost::fusion::detail::apply_transform_result<boost::spirit::traits::build_attribute_sequence<Elements,Context,boost::spirit::traits::sequence_attribute_transform,Iterator,boost::spirit::qi::domain>::element_attribute>,boost::spirit::qi::alternative<boost::fusion::cons<boost::spirit::qi::eol_parser,Cdr>>,boost::mpl::na,boost::mpl::na,boost::mpl::na,boost::mpl::na>'	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\view\transform_view\detail\value_of_impl.hpp	37
Error	C2039	'type': is not a member of 'boost::mpl::apply<boost::fusion::detail::apply_transform_result<boost::spirit::traits::build_attribute_sequence<Elements,Context,boost::spirit::traits::sequence_attribute_transform,Iterator,boost::spirit::qi::domain>::element_attribute>,boost::spirit::qi::kleene<boost::spirit::qi::sequence<boost::fusion::cons<boost::spirit::qi::alternative<boost::fusion::cons<boost::spirit::qi::any_real_parser<T,Policies>,Cdr>>,boost::fusion::cons<boost::spirit::qi::literal_char<boost::spirit::char_encoding::standard,true,false>,boost::fusion::nil_>>>>,boost::mpl::na,boost::mpl::na,boost::mpl::na,boost::mpl::na>'	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\view\transform_view\detail\value_of_impl.hpp	37
Error	C2039	'type': is not a member of 'boost::mpl::apply<boost::fusion::detail::apply_transform_result<boost::spirit::traits::build_attribute_sequence<Elements,Context,boost::spirit::traits::sequence_attribute_transform,Iterator,boost::spirit::qi::domain>::element_attribute>,boost::spirit::qi::lexeme_directive<Subject>,boost::mpl::na,boost::mpl::na,boost::mpl::na,boost::mpl::na>'	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\view\transform_view\detail\value_of_impl.hpp	37
Error	C2039	'type': is not a member of 'boost::mpl::apply<boost::fusion::detail::apply_transform_result<boost::spirit::traits::build_attribute_sequence<Elements,Context,boost::spirit::traits::sequence_attribute_transform,Iterator,boost::spirit::qi::domain>::element_attribute>,boost::spirit::qi::alternative<boost::fusion::cons<boost::spirit::qi::eol_parser,Cdr>>,boost::mpl::na,boost::mpl::na,boost::mpl::na,boost::mpl::na>'	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\view\transform_view\detail\value_of_impl.hpp	37
Error	C2039	'type': is not a member of 'boost::mpl::apply<boost::fusion::detail::apply_transform_result<boost::spirit::traits::build_attribute_sequence<Elements,Context,boost::spirit::traits::sequence_attribute_transform,Iterator,boost::spirit::qi::domain>::element_attribute>,boost::spirit::qi::any_int_parser<T,10,1,-1>,boost::mpl::na,boost::mpl::na,boost::mpl::na,boost::mpl::na>'	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\view\transform_view\detail\value_of_impl.hpp	37
Error	C2039	'type': is not a member of 'boost::mpl::apply<boost::fusion::detail::apply_transform_result<boost::spirit::traits::build_attribute_sequence<Elements,Context,boost::spirit::traits::sequence_attribute_transform,Iterator,boost::spirit::qi::domain>::element_attribute>,boost::spirit::qi::optional<boost::spirit::qi::sequence<boost::fusion::cons<boost::spirit::qi::literal_char<boost::spirit::char_encoding::standard,true,false>,Cdr>>>,boost::mpl::na,boost::mpl::na,boost::mpl::na,boost::mpl::na>'	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\view\transform_view\detail\value_of_impl.hpp	37
Error	C2039	'type': is not a member of 'boost::mpl::apply<boost::fusion::detail::apply_transform_result<boost::spirit::traits::build_attribute_sequence<Elements,Context,boost::spirit::traits::sequence_attribute_transform,Iterator,boost::spirit::qi::domain>::element_attribute>,boost::spirit::qi::kleene<boost::spirit::qi::sequence<boost::fusion::cons<boost::spirit::qi::any_uint_parser<T,10,1,-1>,Cdr>>>,boost::mpl::na,boost::mpl::na,boost::mpl::na,boost::mpl::na>'	shark	G:\ThirdPartyLibraries_VS2015\64Bit\boost-1_59\include\boost-1_59\boost\fusion\view\transform_view\detail\value_of_impl.hpp	37


I think this relates to i

**Comment by skn123** [comment]
Allright, here are my fixes
Problems are in RNet.cpp
size changed to shark::size 
As for the Boost issue; apparently, I had a previous definition
-DBOOST_NO_CXX11_RVALUE_REFERENCES
defined. Once I removed that, the problem did not appear

**Comment by skn123** [comment]
And here is the output
E:\Program_Files\VS2015\VC>G:\Binaries\VS2015\Shark\bin\Release\CVFolds.exe
0 0.0937711
1e-05 0.0883092
2e-05 0.0892161
3e-05 0.0892919
4e-05 0.0897327
5e-05 0.0909876
6e-05 0.0913523
7e-05 0.0921181
8e-05 0.092296
9e-05 0.0923556
RESULTS:
========
best validation error: 0.0883092
best regularization:   1e-05

So, I think you can merge your changes after an independent testing at your end

**Comment by skn123** [comment]
Here is my CMake screenshot. I made my own changes to add Boost 1.59 and hdf5; but that is not relevant for this build 

![image](https://cloud.githubusercontent.com/assets/4594354/11416220/98b27146-9431-11e5-82db-10aabef506d0.png)

**Comment by Ulfgard** [comment]
thank you a lot for your help!
