### ISSUE TITLE
Potential memory bug

### ISSUE THREAD

**Issue by bjornbugge** [Shark-ML/Shark#50]
When I run Memcheck on a simple sample program that runs a few iterations of the CMA algorithm I get the following in the output:
==5452== Mismatched free() / delete / delete []
==5452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==5452==    by 0x63CFD86: syev (syev.hpp:64)
==5452==    by 0x63CFD86: void shark::blas::bindings::syev<shark::blas::matrix<double, shark::blas::row_major>, shark::blas::vector<double> >(shark::blas::matrix_expression<shark::blas::matrix<double, shark::blas::row_major> >&, shark::blas::vector_expression<shark::blas::vector<double> >&) (syev.hpp:83)
==5452==    by 0x63D025C: syev<shark::blas::matrix<double, shark::blas::row_major>, shark::blas::vector<double> > (syev.hpp:56)
==5452==    by 0x63D025C: void shark::blas::eigensymm<shark::blas::matrix<double, shark::blas::row_major>, shark::blas::matrix<double, shark::blas::row_major>, shark::blas::vector<double> >(shark::blas::matrix_expression<shark::blas::matrix<double, shark::blas::row_major> > const&, shark::blas::matrix_expression<shark::blas::matrix<double, shark::blas::row_major> >&, shark::blas::vector_expression<shark::blas::vector<double> >&) (eigenvalues.h:90)
==5452==    by 0x63C95C8: update (MultiVariateNormalDistribution.h:131)
==5452==    by 0x63C95C8: shark::CMA::updatePopulation(std::vector<shark::Individual<shark::blas::vector<double>, double, shark::blas::vector<double> >, std::allocator<shark::Individual<shark::blas::vector<double>, double, shark::blas::vector<double> > > > const&) (CMA.cpp:312)
[ .... rest of stacktrace not Shark ... ]

**Comment by Ulfgard** [comment]
thanks for the report. fixed and ->closed
