### ISSUE TITLE
Shark build for VS2015 (VS/VC++14)

### ISSUE THREAD

**Issue by hhl60492** [Shark-ML/Shark#62]
Hi, I am having trouble building Shark3.0.0 for VS2015.

I have generated the VS project files from CMake and proceeded to build the shark project, however there have been various linker and other errors. Can someone provide a working list of instructions on properly building Shark3.0.0 for VS2015? (I have searched far and wide for complete instructions on install and found none)

That would be most appreciated.

**Comment by Ulfgard** [comment]
a build log would be appreciated. Also: Try 3.1.0 since 3.0.0 some issues on VS got resolved

**Comment by hhl60492** [comment]
Thank you for the reply, I will try to build a Shark 3.1.0 VS project with CMake and I'll get that build log.

**Comment by hhl60492** [comment]
Great success! Building Shark 3.1.0 for VS2015 has completed successfully. 
For future reference:

1. Download Boost VS2015/VS14 binaries, download CMake, Download Shark 3.1.0 follow instructions on building VS2015 project files with CMake on Shark installation guide
2. Open VS2015, open ALL_BUILD configuration properties, include <boostdir>\boost_1_60_0\libs;<boostdir>\boost_1_60_0\boost;<sharkdir>\include\shark\Core on ALL_BUILD VC++ Include Directories
3. Build

**Comment by jaelim** [comment]
@hhl60492 Hello, do you think you can explain in details of step 2. I found ALL_BUILD file in \build folder. But then I'm lost with the next steps.

**Comment by jaelim** [comment]
@hhl60492 regarding boost libs, did you include this lib64-msvc-14.0/ or lib/ folder?
