### ISSUE TITLE
Test 126 - Data_HDF5  fails 

### ISSUE THREAD

**Issue by christian-igel** [Shark-ML/Shark#64]
Hi,
When you do

	make test

you get

	126 - Data_HDF5 (Failed)

because the test looks for an input file:

	m_exampleFileName("./Test/test_data/testfile_for_import.h5“)

What would be the best way to handle this?
The test works fine if called from the Shark root directory.
Cheers,
Christian

**Comment by Ulfgard** [comment]
i think the problem is that we do not define a run directory and thus it is by default $BuildDir/Test/. We should change it to $BuildDir
