### ISSUE TITLE
Build project doc error

### ISSUE THREAD

**Issue by liyu34** [Shark-ML/Shark#66]
Visual Studio 2015.

cannot open tag file D:/Shark-3.1.0/doc/doxygen_pages/tag_files/all.tag for writing

**Comment by jaelim** [comment]
Hello, Do you mind explaining the steps you took to install the shark? I followed the following instruction, but got stuck at building Shark using CMake Gui:

> Windows and Visual Studio
> Dependencies
> 
> First start by download and installing:
> 
>     CMake
>     The most recent boost binaries
> 
> Setting Up Boost
> 
> For simplicity, we assume that you installed boost in C:\locale\boost_1.59\. The boost libraries will be located in a subfolder whose name depends on your compiler (e.g. C:\locale\boost_1.59\lib64-msvc-12.0). Next, you need to tell Windows about the location of the binaries as otherwise compilation will work, but running the compiled binaries will not be possible.
> 
> For this you go to My Computer>Properties>Advanced>Environment Variables>System Variables>Path>Edit>Variable Value and add ;C:\locale\boost_1.59\lib64-msvc-12.0 (or your equivalent path) to the end.
> Installing Shark
> 
>     Download the sources from our Downloads page and unpack them
>     Open the CMake GUI
>     Next to “Where is the source code” set the path to the unpacked Shark location
>     Next to “Where to build the directory” set the path to where you want the Visual Studio project files to be
>     Click on “Add Entry”
>     Add an Entry BOOST_ROOT of type PATH and set it to your boost intall directory (e.g. C:\locale\boost_1.59)
>     Add an Entry BOOST_LIBRARYDIR of type PATH and set it to your boost library directory (e.g. C:\locale\boost_1.59\lib64-msvc-12.0)
>     Set the right Visual Studio compiler and click on Configure (possibly twice) and then on generate

**Comment by jaelim** [comment]
So I'm having trouble understanding what seems to be pretty straightforward to understand, i.e., the last step and executing Configure.

It failed to build because it didn't seem to find the right VS compiler..

**Comment by liyu34** [comment]
Eh...I failed to install shark this time, but I successfully installed shark 3.0(with boost 1.59) once, but it is pretty difficult to describe the whole thing, because of my poor English...
You can contact me with email( liyu34@vip.qq.com ).

**Comment by jaelim** [comment]
@liyu34 Could you please try to explain your steps here as best as you could possibly able to? It would also help the others with the same problem. Thanks.

**Comment by jaelim** [comment]
Could a developer explain how to install Shark in Windows OS? I followed your steps up to the last step where it failed to complete in CMake GUI. Specifically this is what I don't understand: 

> Set the right Visual Studio compiler

Installation doc:
http://image.diku.dk/shark/sphinx_pages/build/html/rest_sources/getting_started/installation.html

**Comment by jaelim** [comment]
The C compiler identification is unknown
The CXX compiler identification is unknown
Check for working C compiler using: Visual Studio 14 2015 Win64
Check for working C compiler using: Visual Studio 14 2015 Win64 -- broken
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "C:/mingw64/bin/gcc.exe" is not able to compile a simple
  test program.

  It fails with the following output:

   Change Dir: C:/Shark/Build/CMakeFiles/CMakeTmp

  

  Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe"
  "cmTC_f7cd4.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"

  Microsoft (R) Build Engine version 14.0.25123.0


  Copyright (C) Microsoft Corporation.  All rights reserved.


  


  Build started 4/4/2016 9:08:33 AM.


  Project "C:\Shark\Build\CMakeFiles\CMakeTmp\cmTC_f7cd4.vcxproj" on node 1
  (default targets).


  C:\Program Files
  (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5):
  error MSB8036: The Windows SDK version 8.1 was not found.  Install the
  required version of Windows SDK or change the SDK version in the project
  property pages or by right-clicking the solution and selecting "Retarget
  solution".  [C:\Shark\Build\CMakeFiles\CMakeTmp\cmTC_f7cd4.vcxproj]


  Done Building Project
  "C:\Shark\Build\CMakeFiles\CMakeTmp\cmTC_f7cd4.vcxproj" (default targets)
  -- FAILED.


  


  Build FAILED.


  


  "C:\Shark\Build\CMakeFiles\CMakeTmp\cmTC_f7cd4.vcxproj" (default target)
  (1) ->


  (Desktop_PlatformPrepareForBuild target) -> 


    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Shark\Build\CMakeFiles\CMakeTmp\cmTC_f7cd4.vcxproj]


  


      0 Warning(s)

      1 Error(s)


  


  Time Elapsed 00:00:00.57


  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:9 (project)


Configuring incomplete, errors occurred!
See also "C:/Shark/Build/CMakeFiles/CMakeOutput.log".
See also "C:/Shark/Build/CMakeFiles/CMakeError.log".

**Comment by liyu34** [comment]
I'm sorry that I hadn't come back to github for a long time, I will comment my steps tomorrow.@jaelim

**Comment by liyu34** [comment]
If you want to build Shark, you have to build boost first. Build boost is very easy, but the thing is if you want to build x64 Shark, you must build x64 boost too. Use ‘Visual Studio x64 Native Tools Command Prompt’ and type command like this `bjam --build-type=complete toolset=msvc-12.0 threading=multi link=static address-model=64`.
And then you can build Shark.
Run CMake, enter Shark's folder, click configure, if CMake told you that it can not find boost's lib, then enable `USE_STATIC_BOOST_LIB`, then click configure another time, no error, click generate.
Up to now, you can enter Shark's dir and open .sln file with Vs.
B.T.W. shark3.1.0 has repaired the mistake that can not build with boost1.60 for it removed a parameter `ice_***`.
