### ISSUE TITLE
`makeastyle` is broken

### ISSUE THREAD

**Issue by wrigleyster** [Shark-ML/Shark#76]
According to the [coding convention][1], astyle should be used to take care of braces, etc., however, the `makeastyle` script in the project root is broken and fails silently. Two of the options are no longer valid `-b` and `--style=ansi` see this [bug report][2] for details on the latter. Additionally astyle now has a recursive option, so the script might be written simply as
```sh
#!/bin/sh
echo "applying astyle to all source and header files"
options="--options=none --style=kr -T -p -U -o -O -n -Q --exclude=CMakeFiles"
astyle $options -r '*.c'
astyle $options -r '*.cc'
astyle $options -r '*.cpp'
astyle $options -r '*.h'
astyle $options -r '*.hpp'
```
or
```sh
#!/bin/sh
echo "applying astyle to all source and header files"
options="--options=none --style=allman -T -p -U -o -O -n -Q --exclude=CMakeFiles"
astyle $options -r '*.c'
astyle $options -r '*.cc'
astyle $options -r '*.cpp'
astyle $options -r '*.h'
astyle $options -r '*.hpp'
```
or something of the like.

Note: astyle does support multiple file-extensions in one call, `astyle -r '*.h' '*.c'`, however if files of one type are not found, astyle will exit with an error, failing to style the files of the other extensions.

[1]: http://image.diku.dk/shark/sphinx_pages/build/html/rest_sources/tutorials/for_developers/codingconvention.html#braces-and-space-character-placement-other-details
[2]: https://sourceforge.net/p/astyle/bugs/146/

**Comment by Ulfgard** [comment]
thank you for the report.

I think we discontinued using astyle after we figured out that it would have a nasty effect on some template construction which would end up being totally unreadable :( we should reflect this in our style guide rather soon...

**Comment by Ulfgard** [comment]
done. sorry that your effort went to waste like this. The tipps were good! But thanks for reporting anyway!
