### ISSUE TITLE
data loaders

### ISSUE THREAD

**Issue by TGlas** [Shark-ML/Shark#87]
The ability to load data from more formats and sources would be nice to have:
- http downloads of csv and sparse data from libSVM website and mldata.org
- read folders full of images (png and jpeg), grayscale and RGB
- read folders full of text documents into Datastd::string?

**Comment by Ulfgard** [comment]
is this fixed now? we have Data/Download

**Comment by TGlas** [comment]
Let's close this for now. Once we have reasonable support for GPUs and deep learning then we probably want to return to loading folders full of images or even videos.
