### ISSUE TITLE
McSVM solver not working when bias is used.

### ISSUE THREAD

**Issue by Ulfgard** [Shark-ML/Shark#90]
When executing the example 

https://github.com/Shark-ML/Shark/blob/master/examples/Supervised/McSvm.tpp

we see horrible results. Here are a few symptons, especially LLW:
1. done after 0 iterations
2. worse results than with bias

I did some preliminary checks and found the following issues:
1. Error in interface usage. The example uses the third argument as a flag with/without bias. however in McSvmLLWTrainer.h this is named "unconstrained" but luckily mapped to the bias flag again in the AbstractSVMTrainer, so only a naming issue (still relevant)
2. in McSvmLLWTrainer.h line 198 the solution properties ar enot fed to the BiasSolver (odd name!), so it is right that the result reads 0 iterations - it is never set to something else.
3. Line 648 in QPMcBoxDecomp bool sumToZero = false should not be a default parameter. As this is not set the LLW property of having sum-to-zero constraints is violated (see documentation McSvmLLWTrainer.h line 80)

**Comment by Ulfgard** [comment]
It is also notable that we do not have tests for the McSVMs with bias.

**Comment by TGlas** [comment]
If "zero iterations" refers to the Rprop steps on the bias then this is an expected result. For the Gaussian kernel with roughly balanced classes the optimal bias value is usually very small, and if may well be smaller than half the default accuracy. Then it will stay at zero, i.e., the solution without bias is within the target accuracy for the setting with bias.

Error in interface usage is a real issue. These trailing bool parameters in the constructors of all SVM trainers with default values are error prone. I am thinking about removing them, and forcing the user to set them explicitly by calling functions. We may leave the "presence of bias" parameter in place.

Of course, there is no excuse for missing unit tests.

**Comment by Ulfgard** [comment]
Hi, i have fixed part of the bug already. I have fixed all obvious bugs outside the solver. It also showed that the 0 iterations are indeed wrong, no solver should return 0 now as we obviously have to return at least the number of iterations it take to solve the bias=0 McSVM.
