### ISSUE TITLE
Buggy doxygen settings for doxylink

### ISSUE THREAD

**Issue by ghisvail** [Shark-ML/Shark#93]
When generating the documentation from `v3.1.1`, sphinx reports that it fails to locate the tag file generated by Doxygen:
```
mkdir build && cd build
cmake .. -DBUILD_DOCUMENTATION=ON
make doc
[...]
WARNING: Could not open tag file <PREFIX>/Shark/doc/doxygen_pages/tag_files/all.tag. Make sure your `doxylink` config variable is set correctly.
```

There is also a large amount of lines of the following form in the output:
```
sh: 1: svnversion: not found
Version of <HEADER> : no version available
```

**Comment by ghisvail** [comment]
I believe the build of the documentation would also benefit from some sort of staging setup, where the complete documentation is put together before install. Right now, this is not the case (see the multiple install commands in `doc/CMakeLists.txt`).

**Comment by Ulfgard** [comment]
Hi, I fixed the two issues mentioned. I am not sure what exactly we should do with the rest.
